/* Proposed application icons, not yet copied into src-tauri/icons. */
(() => {
  const icon = (file, px, alt = '') => `<img src="icon/${file}.png" width="${px}" height="${px}" alt="${alt}"/>`;
  const metal = (px, label = '') => `<span class="icon-proposal__metal" style="--icon-size:${px}px" ${label ? `role="img" aria-label="${label}"` : 'aria-hidden="true"'}><img class="icon-proposal__metal-texture" src="../../overlay/assets/textures/paint.jpg" alt=""/><img class="icon-proposal__metal-mark" src="icon/fdc-icon-lift-mark.svg" alt=""/></span>`;
  const newSizes = file => `<div class="icon-proposal__new-sizes">${[64, 32, 24, 16].map(px => `<span>${icon(file, px)}<small>${px}</small></span>`).join('')}</div>`;
  const splitContext = (name, theme) => `<div class="icon-proposal__context icon-proposal__context--${theme}">${icon('fdc-icon-split', 42)}<span>${name}</span></div>`;
  const paletteContext = (name, theme) => `<div class="icon-proposal__context icon-proposal__context--${theme}">${icon('fdc-icon-chroma-fdc', 42)}<span>${name}</span></div>`;
  const newContext = (name, theme) => `<div class="icon-proposal__context icon-proposal__context--${theme}">${icon('fdc-icon-chroma', 42)}${icon('fdc-icon-spectrum', 42)}<span>${name}</span></div>`;
  const files = ['fdc-icon', 'fdc-icon-lift', 'fdc-icon-pulse'];
  const sizes = [64, 32, 24, 16].map(px => `<tr><th scope="row">${px} px</th>${files.map(file => `<td>${icon(file, px)}</td>`).join('')}</tr>`).join('');
  const context = (name, theme) => `<div class="icon-proposal__context icon-proposal__context--${theme}">${files.map(file => icon(file, 42)).join('')}<span>${name}</span></div>`;
  window.FDC_FOUNDATIONS.push({
    id: 'foundation-icon',
    title: 'App icon · F studies',
    section: 'FOUNDATIONS',
    status: 'proposal',
    proposalLabel: 'FDC ICON / PROPOSAL',
    proposalKicker: 'APP ICON / BOTH THEMES',
    description: 'Split F explores a flat, light-tile icon with established FDC colors. Chroma and earlier studies remain below for comparison; the installed icon remains unchanged.',
    html: `<h2>Split F · flat color study</h2><p class="icon-proposal__intro">A new FDC-authored direction from the supplied simple two-color monogram reference: a large, unmistakable F with two rounded instrument rails on a light rounded tile. The stem stays deep olive; the upper rail is painted olive, and the middle rail is lime. These are existing FDC colors. The reference's letterform and colors are not reproduced.</p>
      <section class="panel icon-proposal__focus">${icon('fdc-icon-split', 256, 'Split F: dark olive F stem, painted olive upper rail and lime middle rail on a warm white rounded tile')}<div><h3>Split F</h3><p class="muted">One bold mark, flat color, and a quiet tile. Judge the 16 and 24 px exports as carefully as the large view.</p>${newSizes('fdc-icon-split')}<p class="muted"><code>--text-bright</code> <code>--surface-deep</code> <code>--paint</code> <code>--accent</code></p></div></section>
      <div class="icon-proposal__contexts">${splitContext('FDC Dark', 'dark')}${splitContext('Light Configuration proposal', 'light')}</div>
      <div class="icon-proposal__files"><a href="icon/fdc-icon-split.svg">Split F SVG ↗</a><a href="icon/fdc-icon-split.png">Split F PNG ↗</a><a href="icon/fdc-icon-split.ico">Split F ICO ↗</a></div>
      <hr class="icon-proposal__divider"/>
      <h2>Chroma, in FDC colors.</h2><p class="icon-proposal__intro">The same bold italic F, now using only established FDC color roles. Its warm spine uses warning, notice, and HUD brake; the top ends in best purple, while the middle moves through readout white into HUD throttle. A newly generated matte metal texture is tinted only with the existing deep and painted surface colors.</p>
      <section class="panel icon-proposal__focus">${icon('fdc-icon-chroma-fdc', 256, 'Chroma FDC: warm warning-to-brake F spine, red-to-best top bar and purple-to-throttle middle bar on a textured dark olive tile')}<div><h3>Chroma · FDC palette</h3><p class="muted">Chroma's connected geometry, with FDC's own color roles and a quiet material tile.</p>${newSizes('fdc-icon-chroma-fdc')}<p class="muted"><code>--warning</code> <code>--notice</code> <code>--telemetry-brake</code> <code>--best</code> <code>--text</code> <code>--telemetry-throttle</code></p></div></section>
      <div class="icon-proposal__contexts">${paletteContext('FDC Dark', 'dark')}${paletteContext('Light Configuration proposal', 'light')}</div>
      <div class="icon-proposal__files"><a href="icon/fdc-icon-chroma-fdc.svg">FDC Chroma SVG ↗</a><a href="icon/fdc-icon-chroma-fdc.png">FDC Chroma PNG ↗</a><a href="icon/fdc-icon-chroma-fdc.ico">FDC Chroma ICO ↗</a><a href="icon/fdc-icon-chroma-fdc-texture.jpg">New tile texture ↗</a></div>
      <hr class="icon-proposal__divider"/>
      <h2>Earlier color studies</h2><p class="icon-proposal__intro">The original Chroma and Spectrum remain here for comparison. Their blue tiles and rainbow colors were exploratory and are not part of FDC's chosen palette.</p>
      <h3>F in color.</h3><p class="icon-proposal__intro">A fresh direction based on the supplied reference: one bold italic F, warm-to-cool color inside the letter, and a deep night-blue tile. These are FDC-authored studies, not a tracing of the reference. Compare the clean ribbon with a faceted, instrument-like version at real Windows sizes.</p>
      <div class="icon-proposal__new-grid">
        <section class="panel icon-proposal__new-card">${icon('fdc-icon-chroma', 224, 'Chroma F: warm gold spine, coral and violet top bar, blue-violet middle bar on a rounded night-blue tile')}<div><h3>Chroma</h3><p class="muted">The simplest read: three connected gradients, one clear F.</p>${newSizes('fdc-icon-chroma')}</div></section>
        <section class="panel icon-proposal__new-card">${icon('fdc-icon-spectrum', 224, 'Spectrum F: gold spine, coral-violet top bar and three blue-violet signal bands on a sparse dotted dark-blue tile')}<div><h3>Spectrum</h3><p class="muted">Layered signal bands and sparse points add the reference's depth.</p>${newSizes('fdc-icon-spectrum')}</div></section>
      </div>
      <p class="muted icon-proposal__new-note">Both use new vector geometry. The blue tile and multicolor rails are exploratory; no app or HUD colors change. At 16 px, judge the overall F silhouette rather than the tiny bands and dots.</p>
      <div class="icon-proposal__contexts">${newContext('FDC Dark', 'dark')}${newContext('Light Configuration proposal', 'light')}</div>
      <div class="icon-proposal__files"><a href="icon/fdc-icon-chroma.svg">Chroma SVG ↗</a><a href="icon/fdc-icon-chroma.png">Chroma PNG ↗</a><a href="icon/fdc-icon-chroma.ico">Chroma ICO ↗</a><a href="icon/fdc-icon-spectrum.svg">Spectrum SVG ↗</a><a href="icon/fdc-icon-spectrum.png">Spectrum PNG ↗</a><a href="icon/fdc-icon-spectrum.ico">Spectrum ICO ↗</a></div>
      <hr class="icon-proposal__divider"/>
      <h2>Less arm. More signal.</h2><p class="icon-proposal__intro">Earlier studies, kept for comparison. Lift keeps both angled cuts in the F, shortens the cream arms, and widens the detached throttle and brake pieces. Their gaps are smaller. The tile carries a quiet olive gradient; the same mark is also shown over FDC's existing painted material below.</p>
      <div class="icon-proposal__variants">
        <section class="panel icon-proposal__variant">${icon('fdc-icon', 192, 'Signal F icon: cream F with a continuous lime upper rail on a rounded dark olive tile')}<h3>Signal F</h3><p class="muted">The minimal baseline. One continuous rail.</p></section>
        <section class="panel icon-proposal__variant">${icon('fdc-icon-lift', 192, 'Lift icon: short cream F arms and wider green and red pieces with close diagonal cuts on an olive gradient tile')}<h3>Signal F · Lift</h3><p class="muted">Shorter cream arms, broader throttle and brake pieces, tighter cuts.</p></section>
        <section class="panel icon-proposal__variant">${icon('fdc-icon-pulse', 192, 'Pulse icon: cream F with one raised step in the lime rail')}<h3>Signal F · Pulse</h3><p class="muted">The previous single-step experiment.</p></section>
      </div>
      <section class="panel"><h3>Background finish</h3><p class="muted icon-proposal__intro">The guide favors a bold symbol and a quiet background at small sizes. These previews hold the same mark and compare only the tile treatment. The gradient is exported as SVG, PNG, and ICO. The material preview reads the existing FDC paint file without copying it into the book.</p><div class="icon-proposal__finish-grid"><figure>${icon('fdc-icon-lift', 160, 'Lift icon with subdued olive gradient')}<figcaption><strong>Olive gradient</strong><span>Portable icon export</span></figcaption><div class="icon-proposal__finish-sizes">${icon('fdc-icon-lift', 32)}${icon('fdc-icon-lift', 16)}</div></figure><figure>${metal(160, 'Lift mark over the FDC painted material')}<figcaption><strong>FDC painted material</strong><span>Book preview only</span></figcaption><div class="icon-proposal__finish-sizes">${metal(32)}${metal(16)}</div></figure></div></section>
      <section class="panel"><h3>At working sizes</h3><p class="muted">Judge the gaps and F silhouette at 24 and 16 px first. Each ICO export includes 16, 24, 32, 48, 64, 128, and 256 px layers.</p><table class="icon-proposal__size-table"><thead><tr><th scope="col">Size</th><th scope="col">Signal F</th><th scope="col">Lift</th><th scope="col">Pulse</th></tr></thead><tbody>${sizes}</tbody></table><h3>Against both themes</h3><div class="icon-proposal__contexts">${context('FDC Dark', 'dark')}${context('Light Configuration proposal', 'light')}</div><div class="icon-proposal__old"><img src="../../src-tauri/icons/icon.png" alt="Current installed FDC icon"/><p class="muted">Current installed icon, for comparison. No proposal replaces it yet.</p></div></section>
      <section class="panel"><h3>Source and handoff</h3><p>Lift is vector geometry based on the user's sketch. Its tile uses a subtle gradient from FDC's olive surfaces; the letter is readout <code>#edf0df</code>, with HUD throttle <code>#69e83f</code> and brake <code>#ff312b</code>. The material preview reuses <code>overlay/assets/textures/paint.jpg</code> and is not an exported icon. SVG is the gradient source; PNG and ICO are exports. No game branding or stock art is added.</p><div class="icon-proposal__files"><a href="icon/fdc-icon-lift.svg">Lift SVG ↗</a><a href="icon/fdc-icon-lift.png">Lift PNG ↗</a><a href="icon/fdc-icon-lift.ico">Lift ICO ↗</a><a href="icon/fdc-icon.svg">Signal F SVG ↗</a><a href="icon/fdc-icon-pulse.svg">Pulse SVG ↗</a></div></section>`
  });
})();
