const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const settingsHtml = fs.readFileSync(path.join(__dirname, 'settings.html'), 'utf8')
const settingsCss = fs.readFileSync(path.join(__dirname, 'settings.css'), 'utf8')
const settingsJs = fs.readFileSync(path.join(__dirname, 'settings.js'), 'utf8')
const overlayHtml = fs.readFileSync(path.join(__dirname, 'index.html'), 'utf8')
const tauriMain = fs.readFileSync(path.join(__dirname, '..', 'src-tauri', 'src', 'main.rs'), 'utf8')
const tauriConfig = fs.readFileSync(path.join(__dirname, '..', 'src-tauri', 'tauri.conf.json'), 'utf8')
const cargoManifest = fs.readFileSync(path.join(__dirname, '..', 'src-tauri', 'Cargo.toml'), 'utf8')

test('Configuration exposes HUD, Garage, Events, Shift Light and Settings tabs', () => {
  const tabs = [...settingsHtml.matchAll(/data-settings-tab="([^"]+)"/g)].map(match => match[1])

  assert.deepEqual(tabs, ['hud', 'shift-light', 'garage', 'events', 'settings'])
  assert.match(settingsHtml, /id="garage-panel"[^>]+data-settings-panel="garage"/)
  assert.match(settingsHtml, /id="garage-grid"[^>]+aria-live="polite"/)
  assert.match(settingsHtml, /id="garage-current-car"/)
  assert.match(settingsHtml, /id="garage-current-variants-toggle"[^>]*>VIEW<\/button>/)
  assert.match(settingsHtml, /id="garage-current-variants"[^>]+class="garage-variants"/)
  assert.match(settingsHtml, /id="garage-cars-count">0 CARS/)
  assert.doesNotMatch(settingsHtml, /ONE CARD PER CAR ORDINAL/)
  assert.doesNotMatch(settingsHtml, /garage-current-title[^]*LAST USED/)
  assert.match(settingsJs, /load_garage_snapshot/)
  assert.match(settingsJs, /rename_garage_car/)
  assert.match(settingsJs, /garage-current-car__input/)
  assert.match(settingsJs, /garage-performance--/)
  assert.match(settingsJs, /garage-current-car__group/)
  assert.match(settingsJs, /garage-current-car__drivetrain/)
  assert.match(settingsJs, /garage-current-car__cylinders/)
  assert.match(settingsJs, /details\.append\(garageCurrentVariantsToggle\)/)
  assert.match(settingsJs, /garageVariantsFor/)
  assert.match(settingsJs, /garage-variant-row__cylinders/)
  assert.match(settingsJs, /\?\? vehicle\?\.cylinders/)
  assert.match(settingsJs, /garage-current-variants-toggle/)
  assert.match(settingsJs, /garageCurrentVariantsToggle\?\.addEventListener\('click', toggleGarageVariants\)/)
  assert.match(settingsJs, /event\.key !== 'Escape'/)
  assert.match(settingsJs, /garage-current-car__input/)
  assert.doesNotMatch(settingsJs, /garage-shift-light/)
  assert.doesNotMatch(settingsJs, /Duplicate/u)
  assert.doesNotMatch(settingsJs, /appendGarageShiftLight/)
  assert.match(settingsJs, /garage-card--latest/)
  assert.match(settingsJs, /latest\.textContent = 'LAST USED'/)
  assert.doesNotMatch(settingsJs, /input\.className = 'garage-card__name'/)
  assert.match(settingsCss, /\.garage-variants\s*\{[\s\S]*grid-auto-rows:\s*36px[\s\S]*max-height:\s*432px[\s\S]*overflow-y:\s*auto/)
  assert.match(settingsCss, /\.garage-variants\s*\{[\s\S]*width:\s*100%[\s\S]*border:\s*1px solid/)
  assert.match(settingsCss, /\.garage-variant-row\s*\{[\s\S]*justify-content:\s*flex-start/)
  assert.match(settingsCss, /\.garage-variant-row\s*\{[\s\S]*border-left:\s*3px solid var\(--garage-rank-color\)/)
  assert.doesNotMatch(settingsCss, /\.garage-current-variants-toggle\s*\{[^}]*position:\s*absolute/)
  assert.match(settingsCss, /\.garage-current-variants-toggle\s*\{[\s\S]*margin-left:\s*auto/)
})

test('Events keeps the existing navigation and exposes the create/detail flow', () => {
  assert.match(settingsHtml, /id="events-tab"[^>]+data-settings-tab="events"/)
  assert.match(settingsHtml, /id="events-panel"[^>]+data-settings-panel="events"/)
  assert.match(settingsHtml, /id="events-grid"[^>]+aria-live="polite"/)
  assert.match(settingsHtml, /id="events-create-toggle"[^>]+aria-controls="events-create-area"/)
  assert.match(settingsHtml, /id="events-create-area"[^>]+hidden/)
  assert.ok(settingsHtml.indexOf('id="events-create-area"') < settingsHtml.indexOf('id="events-grid"'))
  assert.match(settingsHtml, /id="events-discard-dialog"[^>]+role="alertdialog"[^>]+hidden/)
  assert.match(settingsHtml, /id="events-discard-yes"[^>]*>YES<\/button>/)
  assert.match(settingsHtml, /id="events-discard-no"[^>]*>NO<\/button>/)
  for (const id of ['event-name', 'event-class', 'event-route-type', 'event-mode', 'event-notes']) {
    assert.match(settingsHtml, new RegExp(`id="${id}"`))
  }
  const formStart = settingsHtml.indexOf('id="events-create-form"')
  const formEnd = settingsHtml.indexOf('</form>', formStart)
  const eventsForm = settingsHtml.slice(formStart, formEnd)
  assert.ok(eventsForm.indexOf('id="event-name"') < eventsForm.indexOf('id="event-mode"'))
  assert.ok(eventsForm.indexOf('id="event-mode"') < eventsForm.indexOf('id="event-route-type"'))
  assert.ok(eventsForm.indexOf('id="event-route-type"') < eventsForm.indexOf('id="event-class"'))
  assert.ok(eventsForm.indexOf('id="event-class"') < eventsForm.indexOf('id="event-notes"'))
  assert.match(settingsHtml, /id="events-detail-view"[^>]+hidden/)
  assert.match(settingsHtml, /id="events-detail-back"[^>]*>BACK<\/button>/)
  assert.match(settingsHtml, /id="events-detail-title"/)
  assert.match(settingsHtml, /id="events-detail-summary"[^>]+aria-label="Event details"/)
  assert.match(settingsHtml, /id="events-detail-notes"[^>]+hidden/)
  assert.match(settingsHtml, /id="events-detail-absolute-best"/)
  assert.doesNotMatch(settingsHtml, /id="events-detail-hint"|id="events-detail-card"|id="events-detail-metadata"/)
  assert.doesNotMatch(settingsHtml, /id="events-detail-archive"/)
  assert.match(settingsHtml, /id="events-detail-delete"/)
  assert.match(settingsHtml, /id="events-run-view"[^>]+hidden/)
  assert.match(settingsHtml, /id="events-run-back"[^>]*>BACK<\/button>/)
  assert.match(settingsHtml, /id="events-run-title"/)
  assert.match(settingsHtml, /id="events-run-summary"[^>]+aria-label="Event details"/)
  assert.match(settingsHtml, /id="events-run-bht"/)
  assert.match(settingsHtml, /id="events-run-lap-sort"[^>]+aria-sort="descending"/)
  assert.match(settingsHtml, /id="events-run-laps"/)
  assert.match(settingsJs, /call\('create_event', payload\)/)
  assert.match(settingsJs, /route: eventRouteType\.value/)
  assert.match(settingsJs, /call\('load_events'\)/)
  assert.match(settingsJs, /call\('load_event'/)
  assert.match(settingsJs, /call\('rename_event'/)
  assert.match(settingsJs, /function nativeEventId\(value\)/)
  assert.match(settingsJs, /call\('rename_event', \{ eventId: nativeEventId\(event\.id\), name \}\)/)
  assert.doesNotMatch(settingsJs, /archive_event|archiveCurrentEvent|archived_at/)
  assert.match(settingsJs, /call\('delete_event'/)
  assert.match(settingsJs, /call\('delete_event', \{ eventId: nativeEventId\(event\.id\) \}\)/)
  assert.match(settingsJs, /globalScope\.confirm\(/)
  assert.match(settingsJs, /function eventCreateFormHasContent\(\)/)
  assert.match(settingsJs, /function requestEventsCreateClose\(\)/)
  assert.match(settingsJs, /if \(eventsView === 'library' && eventsCreateOpen\)/)
  assert.match(settingsJs, /events-detail-view__title-input/)
  assert.match(settingsJs, /events-detail-view__badge--mode/)
  assert.match(settingsJs, /events-detail-view__badge--class/)
  assert.match(settingsJs, /eventsDetailNotes\.hidden = !event\.notes/)
  assert.doesNotMatch(settingsJs, /function renderEventDetail\([^]*renderEventCard\(event, true\)/)
  assert.match(settingsJs, /id\.textContent = `#\$\{event\.id\}`/)
  assert.match(settingsJs, /function eventAbsoluteBestTimeMs\(/)
  assert.match(settingsJs, /eventsDetailAbsoluteBest\.textContent = formatRunTime\(eventAbsoluteBestTimeMs\(\)\)/)
  assert.doesNotMatch(settingsJs, /events-card__image/)
  assert.doesNotMatch(settingsJs, /copyEventId|events-card__copy|clipboard\.writeText/)
  assert.match(settingsJs, /eventsView === 'detail'/)
  assert.match(settingsJs, /function openEventRun\(id\)/)
  assert.match(settingsJs, /function closeEventRun\(\)/)
  assert.match(settingsJs, /function runBestHypotheticalTimeMs\(run\)/)
  assert.match(settingsJs, /function savedRunTimeLabel\(run\)/)
  assert.match(settingsJs, /RESULT \$\{formatRunTime\(run\.finalTimeMs\)\}/)
  assert.match(settingsJs, /LAST \$\{formatRunTime\(lap\.timeMs\)\}/)
  assert.match(settingsJs, /eventRunLapSortDirection = 'desc'/)
  assert.match(settingsJs, /value\.dataset\.tone = tone/)
  assert.match(settingsCss, /\.settings-tabs\s*\{[\s\S]*grid-template-columns:\s*repeat\(5,/)
  assert.match(settingsCss, /\.events-grid\s*\{[\s\S]*grid-template-columns:\s*repeat\(auto-fit/)
  assert.match(settingsCss, /\.events-card__id\s*\{[\s\S]*font-size:\s*28px/)
  assert.match(settingsCss, /\.events-discard-dialog \.events-discard-dialog__no\s*\{[\s\S]*background:\s*#69e83f/)
  assert.match(settingsCss, /\.events-discard-dialog \.events-discard-dialog__yes:hover[\s\S]*background:\s*#ef4444/)
  assert.doesNotMatch(settingsCss, /events-card__image/)
  assert.doesNotMatch(settingsCss, /events-card__copy/)
  assert.match(settingsCss, /\.events-card\[data-event-mode="any"\][\s\S]*#f97316/)
  assert.match(settingsCss, /\.events-card\[data-event-mode="rivals"\][\s\S]*#7dd3fc/)
  assert.match(settingsCss, /\.events-card\[data-event-mode="online"\][\s\S]*#facc15/)
  assert.match(settingsCss, /\.events-card\[data-event-mode="eventlab"\][\s\S]*#ffffff/)
  assert.match(settingsCss, /\.events-card\[data-event-mode="official"\][\s\S]*#ef4444/)
  assert.match(settingsCss, /\.events-card\[data-event-mode="blueprint"\][\s\S]*#c084fc/)
  assert.match(settingsJs, /events-card__badge--class/)
  assert.match(settingsJs, /meta\.append\(mode, route, eventClass\)/)
  assert.match(settingsCss, /\.events-card__badge--class\[data-event-class="B"\][\s\S]*#f97316/)
  assert.match(settingsCss, /\.events-detail-view__badge--class\[data-event-class="A"\][\s\S]*#ef4444/)
  assert.match(settingsCss, /\.events-detail-view__badge--class\[data-event-class="S1"\][\s\S]*#c084fc/)
  assert.match(settingsCss, /\.events-run-table__time\[data-tone="best"\][\s\S]*#c084fc/)
  assert.match(settingsCss, /\.events-run-table__time\[data-tone="second"\][\s\S]*#69e83f/)
  assert.match(settingsCss, /\.events-detail-view__absolute-best-value\s*\{[\s\S]*#c084fc/)
})

test('Event recorder uses the compact idle control and local run timestamps', () => {
  assert.doesNotMatch(settingsHtml, /event-recorder__eyebrow|RUN CAPTURE/)
  assert.match(settingsHtml, /id="event-recorder-status"[^>]+hidden/)
  assert.match(settingsHtml, /id="event-recorder-toggle"[^>]*>RECORD RUN<\/button>/)
  assert.match(settingsJs, /eventRecorderStatus\.hidden = !recording && !finalizing/)
  assert.match(settingsJs, /eventRecorderToggle\.textContent = finalizing \? 'FINALIZING' : recording \? 'STOP' : 'RECORD RUN'/)
  assert.match(settingsJs, /eventRecorderToggle\.disabled = recordingAnotherEvent \|\| finalizing/)
  assert.match(settingsHtml, /data-tone="warning"[^>]*>For Sprint Racing, press STOP in free roam or before starting a new race\. The results screen can report an imprecise final time\.<\/p>/)
  assert.match(settingsJs, /For Sprint Racing, press STOP in free roam or before starting a new race\. The results screen can report an imprecise final time\./)
  assert.match(settingsJs, /eventRecorderHint\.dataset\.tone = !recordingAnotherEvent && !finalizing \? 'warning' : ''/)
  assert.match(settingsCss, /\.event-recorder__hint\[data-tone="warning"\][\s\S]*#f97316/)
  assert.match(settingsJs, /getHours\(\).*getMinutes\(\).*getSeconds\(\)/s)
  assert.match(settingsCss, /\.event-recorder\s*\{[\s\S]*border: 1px solid rgb\(226 232 240 \/ 18%\);[\s\S]*background: rgb\(226 232 240 \/ 5%\)/)
  assert.match(settingsCss, /\.event-recorder__record\s*\{[\s\S]*background: #69e83f/)
  assert.match(settingsCss, /\.settings-button--danger[\s\S]*color: #ff827d/)
})

test('Events expose deterministic persisted list sorting and in-memory run sorting', () => {
  assert.match(settingsHtml, /id="events-sort"[^>]+aria-label="Sort events"/)
  assert.deepEqual(
    [...settingsHtml.matchAll(/<option value="([^"]+)">/g)].map(match => match[1]).filter(value => value.includes('recorded') || value.startsWith('id-')),
    ['id-desc', 'id-asc', 'last-recorded-desc', 'last-recorded-asc']
  )
  assert.match(settingsJs, /const EVENTS_SORT_STORAGE_KEY = 'fdc\.events-sort\.v1'/)
  assert.match(settingsJs, /localStorage\.setItem\(EVENTS_SORT_STORAGE_KEY, JSON\.stringify\(value\)\)/)
  assert.match(settingsJs, /let eventRunsSort = \{ key: 'date', direction: 'desc' \}/)
  assert.match(settingsHtml, /data-run-sort="id"/)
  assert.match(settingsHtml, /data-run-sort="best"/)
  assert.match(settingsHtml, /data-run-sort="date"/)
  assert.match(settingsJs, /run\?\.runType === 'sprint'/)
  assert.match(settingsJs, /applyEventRunDates\(normalizeEventRunsPayload\(await call\('load_event_runs'/)
})

test('Event lap rows expose trace details and time-weighted pedal statistics', () => {
  assert.match(settingsHtml, /events-run-table__caption[^>]*>Select a lap row to view its trace and pedal statistics\.<\/caption>/)
  assert.match(settingsJs, /function normalizeTracePoints\(value\)/)
  assert.doesNotMatch(settingsJs, /TRACE · X \/ Z/)
  assert.match(settingsJs, /const positionX = finiteNumber/)
  assert.match(settingsJs, /const positionZ = finiteNumber/)
  assert.match(settingsJs, /function traceStats\(points/)
  assert.match(settingsJs, /totals\[traceState\(points\[index\]\)\] \+= elapsed/)
  assert.match(settingsJs, /const remaining = Number\.isFinite\(lapTimeMs\)/)
  assert.match(settingsJs, /totals\[traceState\(points\.at\(-1\)\)\] \+= remaining/)
  assert.match(settingsJs, /if \(normalizePedal\(point\?\.brake\) >= 0\.05\) return 'brake'/)
  assert.match(settingsJs, /events-lap-detail__trace events-lap-detail__trace--\$\{traceState\(points\[index\]\)\}/)
  assert.match(settingsJs, /events-lap-detail__sector-tick/)
  assert.match(settingsJs, /events-lap-detail__stat--\$\{key\}/)
  assert.match(settingsJs, /if \(expandedEventRunLap !== null\)/)
  assert.match(settingsJs, /row\.setAttribute\('aria-expanded', String\(expanded\)\)/)
  assert.match(settingsJs, /call\('load_event_run', \{ runId: nativeRunId \}\)/)
  assert.match(settingsCss, /\.events-lap-detail\s*\{[\s\S]*grid-template-columns: minmax\(0, 1\.9fr\) minmax\(180px, 0\.85fr\)/)
  assert.match(settingsCss, /\.events-lap-detail__trace\s*\{[\s\S]*stroke-width: 2\.4;/)
  assert.match(settingsCss, /\.events-lap-detail__trace--throttle\s*\{\s*stroke: #69e83f;/)
  assert.match(settingsCss, /\.events-lap-detail__trace--brake\s*\{\s*stroke: #ef4444;/)
  assert.match(settingsCss, /\.events-lap-detail__trace--coast\s*\{\s*stroke: #facc15;/)
  assert.match(settingsCss, /\.events-lap-detail__sector-tick\s*\{\s*stroke: #f8fafc;/)
  assert.match(settingsCss, /\.events-lap-detail__sector-label\s*\{\s*fill: #f8fafc;/)
  assert.doesNotMatch(settingsJs, /events-lap-detail__stat-key/)
  assert.match(settingsCss, /\.events-run-view__metric\s*\{[\s\S]*align-items: center;/)
})

test('Engine telemetry keeps the compact panel order and one visibility toggle', () => {
  const sections = [...overlayHtml.matchAll(/<section id="(hud-[^"]+)"/g)].map(match => match[1])
  const components = [...settingsHtml.matchAll(/data-hud-component="([^"]+)"/g)].map(match => match[1])

  assert.deepEqual(sections, ['hud-tires', 'hud-pedals', 'hud-steering', 'hud-gear', 'hud-engine', 'hud-history'])
  assert.deepEqual(components, ['tires', 'pedals', 'steering', 'gear', 'engine', 'history'])
  assert.match(settingsHtml, /<strong>Engine \/ Boost<\/strong>/)
  assert.match(settingsHtml, /<small>Boost, power and torque data<\/small>/)
  assert.match(overlayHtml, /id="engine-boost"[^>]+aria-label="Boost pressure"/)
  assert.match(overlayHtml, /id="engine-power"[^>]+aria-label="Engine power"/)
  assert.match(overlayHtml, /id="engine-torque"[^>]+aria-label="Engine torque"/)
})

test('Engine visibility is part of the safe HUD component contract', () => {
  const preferences = fs.readFileSync(path.join(__dirname, 'hud-preferences.js'), 'utf8')

  assert.match(preferences, /const COMPONENTS = \['tires', 'pedals', 'steering', 'gear', 'engine', 'history'\]/)
  assert.match(preferences, /engine: '116px'/)
  assert.match(tauriMain, /"tires" \| "pedals" \| "steering" \| "gear" \| "engine" \| "history"/)
})

test('telemetry status stays separate and right-aligned above the setup card', () => {
  const settingsPanelIndex = settingsHtml.indexOf('id="settings-panel"')
  const telemetryStatusIndex = settingsHtml.indexOf('id="telemetry-status"')
  const routeCardIndex = settingsHtml.indexOf('id="telemetry-route-card"')
  const headerIndex = settingsHtml.indexOf('class="settings-header"')

  assert.ok(settingsPanelIndex >= 0)
  assert.ok(headerIndex >= 0)
  assert.ok(telemetryStatusIndex > headerIndex)
  assert.ok(routeCardIndex > telemetryStatusIndex)
  assert.ok(telemetryStatusIndex < settingsPanelIndex)
  assert.ok(routeCardIndex < settingsPanelIndex)
  assert.match(settingsHtml, /class="settings-header__connection"[\s\S]*id="telemetry-status"[\s\S]*id="telemetry-route-card"/)
  assert.match(settingsCss, /\.settings-header__connection > \.telemetry-status[\s\S]*justify-content: flex-end[\s\S]*width: 100%/)
  assert.match(settingsCss, /#telemetry-route-detail\s*\{\s*margin-top: 0;/)
  assert.match(settingsHtml, /class="telemetry-setup-guide"[\s\S]*Settings → HUD and Gameplay → Telemetry/)
  assert.match(settingsHtml, /Data Out IP Address[\s\S]*127\.0\.0\.1/)
  assert.match(settingsHtml, /Data Out IP Port[\s\S]*5301/)
  const setupGuide = settingsHtml.slice(settingsHtml.indexOf('class="telemetry-setup-guide"'), settingsHtml.indexOf('id="telemetry-route-retry"'))
  assert.equal((setupGuide.match(/<li>/g) || []).length, 4)
  assert.doesNotMatch(setupGuide, /Return to the game and start driving/u)
  assert.doesNotMatch(settingsHtml, /id="telemetry-route-endpoint"|id="telemetry-route-label"/)
  assert.doesNotMatch(settingsJs, /telemetryRouteEndpoint|telemetryRouteLabel|telemetryRouteDetail|telemetryRouteWarning/u)
  assert.doesNotMatch(overlayHtml, /telemetry-route-badge/)
})

test('Configuration title sits directly below the product name', () => {
  assert.match(settingsHtml, /class="settings-header__brand"[\s\S]*Feedback-Driven Companion[\s\S]*<h1>CONFIGURATION<\/h1>/u)
  assert.doesNotMatch(settingsHtml, /Configure the overlay and Shift Light\./u)
})

test('Configuration window title reflects the active section and build version without game branding', () => {
  const configuredTitles = JSON.parse(tauriConfig).app.windows.map(window => window.title)

  assert.deepEqual(
    [...settingsHtml.matchAll(/data-settings-tab="([^"]+)"/g)].map(match => match[1]),
    ['hud', 'shift-light', 'garage', 'events', 'settings']
  )
  assert.deepEqual(configuredTitles, ['FDC · HUD', 'FDC · HUD'])
  assert.doesNotMatch(`${configuredTitles.join(' ')} ${overlayHtml}`, /Forza Horizon 6 HUD/u)
  assert.match(settingsJs, /const SETTINGS_WINDOW_CONTEXTS = Object\.freeze\(/)
  assert.match(settingsJs, /call\('set_settings_window_context', \{ context: tabName \}\)/)
  assert.match(tauriMain, /fn settings_window_context_label\(context: &str\) -> Option<&'static str>/)
  assert.match(tauriMain, /"hud" => Some\("HUD"\)/)
  assert.match(tauriMain, /"garage" => Some\("GARAGE"\)/)
  assert.match(tauriMain, /"events" => Some\("EVENTS"\)/)
  assert.match(tauriMain, /"shift-light" => Some\("SHIFT LIGHT"\)/)
  assert.match(tauriMain, /"settings" => Some\("SETTINGS"\)/)
  assert.match(tauriMain, /fn settings_window_title\(context: &str\) -> String/)
  assert.match(tauriMain, /format!\("FDC · \{context\} · v\{\}", get_app_version\(\)\)/)
  assert.match(tauriMain, /fn set_settings_window_context\(app: AppHandle, context: String\)/)
})

test('Configuration exposes only the Direct Data Out receiver', () => {
  assert.match(settingsHtml, /DIRECT DATA OUT/)
  assert.match(settingsHtml, /127\.0\.0\.1/)
  assert.match(settingsHtml, /5301/)
  assert.doesNotMatch(settingsHtml, /telemetry-source|co-driver|Suite|WebSocket/u)
  assert.doesNotMatch(settingsJs, /HudConnection|set_telemetry_source|selectTelemetrySource/u)
  assert.match(settingsJs, /call\('retry_direct_source'\)/u)
  assert.match(tauriMain, /fn retry_direct_source/u)
})

test('Settings exposes Configuration priority and speed unit preferences', () => {
  const settingsPanelIndex = settingsHtml.indexOf('id="settings-panel"')
  const displayPreferencesScriptIndex = settingsHtml.indexOf('src="display-preferences.js"')
  const settingsScriptIndex = settingsHtml.indexOf('src="settings.js"')
  const settingsPanel = settingsHtml.slice(settingsPanelIndex)

  assert.ok(settingsPanelIndex >= 0)
  assert.match(settingsHtml, /<section class="display-settings" aria-label="Display settings">/)
  assert.doesNotMatch(settingsHtml, /DISPLAY SETTINGS|WINDOW \+ SPEED FORMAT/u)
  assert.match(settingsHtml, /name="speed-unit" value="kmh"/)
  assert.match(settingsHtml, /name="speed-unit" value="mph"/)
  assert.match(settingsHtml, /id="configuration-always-on-top" class="visibility-toggle" type="button"/)
  assert.match(settingsHtml, /<strong>SHOW HUD WITH TELEMETRY<\/strong>/)
  assert.match(settingsHtml, /id="show-hud-with-telemetry" class="visibility-toggle" type="button"[^>]*aria-pressed="true"/)
  assert.ok(settingsHtml.indexOf('id="show-hud-with-telemetry"') > settingsPanelIndex)
  assert.match(settingsJs, /showHudWithTelemetry/)
  assert.match(settingsJs, /set_configuration_always_on_top/)
  assert.match(tauriMain, /fn set_configuration_always_on_top/)
  assert.doesNotMatch(settingsPanel, /telemetry-settings|telemetry-route-card|DIRECT DATA OUT.*OFFLINE/u)
  assert.ok(displayPreferencesScriptIndex >= 0)
  assert.ok(settingsScriptIndex > displayPreferencesScriptIndex)
})

test('Shift Light exposes separate redline and FDC cue controls in the Shift Light tab', () => {
  const shiftLightPanelIndex = settingsHtml.indexOf('id="shift-light-panel"')
  const redlineIndex = settingsHtml.indexOf('id="redline-brightness"')
  const redlineResetIndex = settingsHtml.indexOf('id="redline-brightness-reset"')
  const cueToggleIndex = settingsHtml.indexOf('id="fdc-shift-light-enabled"')
  const brightnessIndex = settingsHtml.indexOf('id="shift-light-brightness"')
  const settingsPanelIndex = settingsHtml.indexOf('id="settings-panel"')

  assert.ok(shiftLightPanelIndex >= 0)
  assert.ok(redlineIndex > shiftLightPanelIndex)
  assert.ok(redlineResetIndex > shiftLightPanelIndex)
  assert.ok(cueToggleIndex > redlineResetIndex)
  assert.ok(brightnessIndex > shiftLightPanelIndex)
  assert.ok(brightnessIndex > cueToggleIndex)
  assert.ok(brightnessIndex < settingsPanelIndex)
  assert.match(settingsHtml, /<h3 id="redline-brightness-title">REDLINE BRIGHTNESS<\/h3>/)
  assert.match(settingsHtml, /id="redline-brightness-value"[^>]*>80%<\/output>/)
  assert.match(settingsHtml, /id="redline-brightness" type="range" min="0" max="100" step="5" value="80"/)
  assert.match(settingsHtml, /id="redline-brightness-reset"[^>]*type="button"[^>]*disabled>RESET<\/button>/)
  assert.match(settingsHtml, /id="fdc-shift-light-enabled" class="visibility-toggle" type="button"[^>]*aria-pressed="true"/)
  assert.match(settingsHtml, /<small>FDC shows the optimal shift cue in purple\.<\/small>/)
  assert.match(settingsHtml, /<h3 id="shift-light-brightness-title">FDC SHIFT LIGHT BRIGHTNESS<\/h3>/)
  assert.match(settingsHtml, /class="shift-light-brightness-card"/)
  assert.match(settingsHtml, /id="shift-light-brightness" type="range" min="0" max="100" step="5" value="80"/)
  assert.match(settingsHtml, /<span class="calibration-label">LEARNED CEILING<\/span>/)
  assert.match(settingsHtml, /id="shift-light-usable-ceiling"/)
  assert.match(settingsHtml, /The usable redline is the safe shift target/)
  assert.match(settingsHtml, /<dt>POTENTIAL<\/dt>/)
  assert.match(settingsHtml, /A negative result simply leaves the safe redline target in place/)
  assert.match(settingsJs, /redlineBrightness/)
  assert.match(settingsJs, /fdcShiftLightEnabled/)
})

test('HUD opacity appears before HUD controls and resets to its 80 percent default', () => {
  const hudOpacityIndex = settingsHtml.indexOf('id="hud-opacity"')
  const layoutListIndex = settingsHtml.indexOf('<div class="layout-list">')

  assert.ok(hudOpacityIndex >= 0)
  assert.ok(hudOpacityIndex < layoutListIndex)
  assert.match(settingsHtml, /id="hud-opacity" type="range" min="1" max="100" step="1" value="80"/)
  assert.match(settingsHtml, /id="hud-opacity-reset" class="settings-button hud-opacity-reset" type="button" disabled>RESET<\/button>/)
  assert.match(settingsJs, /HUD OPACITY RESET TO \$\{next\.hudOpacity\}%/)
  assert.match(settingsJs, /hudOpacityReset\.disabled = pending \|\| displayPreferences\.hudOpacity === DEFAULT_HUD_OPACITY/)
  assert.match(settingsCss, /\.hud-opacity-reset\.is-dirty:not\(:disabled\)[\s\S]*?#facc15/)
})

test('HUD heading has no redundant position and visibility label, and status uses a fixed footer', () => {
  assert.doesNotMatch(settingsHtml, /POSITION \+ VISIBILITY/)
  assert.match(settingsHtml, /<footer class="settings-footer"[^>]*>[\s\S]*id="settings-status"[^>]*>[\s\S]*id="app-version"[^>]*>VERSION UNAVAILABLE<\/span>[\s\S]*<\/footer>/)
  assert.doesNotMatch(settingsHtml, /v\d+\.\d+\.\d+/)
  assert.doesNotMatch(settingsJs, /v\d+\.\d+\.\d+/)
  assert.match(settingsJs, /getElementById\('settings-status'\)/)
  assert.match(settingsJs, /call\('get_app_version'\)/)
  assert.match(settingsJs, /appVersion\.textContent = `v\$\{normalizedVersion\}`/)
  assert.match(tauriMain, /fn get_app_version\(\) -> &'static str/)
  assert.match(cargoManifest, /^version = "\d+\.\d+\.\d+"$/m)
  assert.equal(Object.hasOwn(JSON.parse(tauriConfig), 'version'), false)
  assert.match(settingsCss, /--settings-footer-height:\s*52px;/)
  assert.match(settingsCss, /\.settings-shell\s*{[\s\S]*?padding:\s*28px 30px calc\(26px \+ var\(--settings-footer-height\)\);/)
  assert.match(settingsCss, /\.settings-footer\s*{[\s\S]*?position:\s*fixed;[\s\S]*?height:\s*var\(--settings-footer-height\);[\s\S]*?border-top:[\s\S]*?background:\s*#090b0e;/)
  assert.doesNotMatch(settingsCss, /\.settings-status\s*{[^}]*position:\s*fixed;/)
})

test('Configuration persists and applies display preferences through the shared contract', () => {
  assert.match(settingsJs, /displayPreferencesApi\?\.read/)
  assert.match(settingsJs, /displayPreferencesApi\.normalize/)
  assert.match(settingsJs, /displayPreferencesApi\.write\(next\)/)
  assert.match(settingsJs, /call\('set_display_preferences', \{\s*speedUnit: next\.speedUnit,\s*redlineBrightness: next\.redlineBrightness,\s*shiftLightBrightness: next\.shiftLightBrightness,\s*hudOpacity: next\.hudOpacity,\s*fdcShiftLightEnabled: next\.fdcShiftLightEnabled,\s*showHudWithTelemetry: next\.showHudWithTelemetry\s*\}\)/)
  assert.match(settingsJs, /displayPreferences = previous\s*displayPreferencesApi\.write\(previous\)\s*renderDisplayPreferences\(previous\)/)
  assert.match(settingsJs, /redlineBrightness: DEFAULT_REDLINE_BRIGHTNESS/)
  assert.match(settingsJs, /fdcShiftLightEnabled: true/)
  assert.match(settingsJs, /showHudWithTelemetry: true/)
  assert.match(settingsJs, /configurationAlwaysOnTop: true/)
})

test('Configuration keeps its default size and exposes standard Windows controls', () => {
  const settingsWindow = JSON.parse(tauriConfig).app.windows.find(window => window.label === 'settings')

  assert.deepEqual({ width: settingsWindow.width, height: settingsWindow.height }, { width: 820, height: 620 })
  assert.equal(settingsWindow.minimizable, true)
  assert.equal(settingsWindow.maximizable, true)
  assert.equal(settingsWindow.alwaysOnTop, true)
})

test('Configuration restores its last on-screen position with its size', () => {
  assert.match(tauriMain, /SettingsWindowState/)
  assert.match(tauriMain, /WindowEvent::Resized\(_\) \| WindowEvent::Moved\(_\)/)
  assert.match(tauriMain, /window\.outer_position\(\)/)
  assert.match(tauriMain, /app\s*\.available_monitors\(\)/)
  assert.match(tauriMain, /window\.set_position\(position\)/)
  assert.match(tauriMain, /serde\(default\)/)
})

test('Configuration opens every time the HUD starts', () => {
  assert.match(tauriMain, /window\.show\(\)\?;\s*show_settings\(app\.handle\(\)\)\?;/)
  assert.doesNotMatch(tauriMain, /settings-first-launch-complete/)
})

test('tray has one Configuration action and no calibration reset action', () => {
  assert.match(tauriMain, /\.text\("settings", "Configuration"\)/)
  assert.doesNotMatch(tauriMain, /reset-shift/)
  assert.match(tauriMain, /\.text\("quit", "Quit"\)/)
})

test('Configuration replays Shift Light state and waits for the real reset result', () => {
  assert.match(settingsJs, /hud_shift_light_reset_result/)
  assert.match(settingsJs, /call\('sync_shift_light_status'\)/)
  assert.equal(settingsJs.match(/CALIBRATION RESET COMPLETE/g)?.length, 1)
  assert.match(tauriMain, /fn sync_shift_light_status/)
})
