const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { readResolvedStylesheet } = require('../tools/stylesheet-tokens.cjs')

const settingsHtml = fs.readFileSync(path.join(__dirname, 'settings.html'), 'utf8')
const settingsCss = readResolvedStylesheet('settings.css')
// Interface roles are asserted by token; preserved meanings (modes, classes, map layers) by value.
const settingsStyles = fs.readFileSync(path.join(__dirname, 'settings.css'), 'utf8')
const settingsJs = fs.readFileSync(path.join(__dirname, 'settings.js'), 'utf8')
const overlayHtml = fs.readFileSync(path.join(__dirname, 'index.html'), 'utf8')
const tauriMain = fs.readFileSync(path.join(__dirname, '..', 'src-tauri', 'src', 'main.rs'), 'utf8')
const tauriConfig = fs.readFileSync(path.join(__dirname, '..', 'src-tauri', 'tauri.conf.json'), 'utf8')
const cargoManifest = fs.readFileSync(path.join(__dirname, '..', 'src-tauri', 'Cargo.toml'), 'utf8')

test('Every Configuration tab has a one-paragraph intro in the header and Settings states where data lives', () => {
  const header = settingsHtml.slice(settingsHtml.indexOf('<header class="settings-header">'), settingsHtml.indexOf('</header>'))
  for (const panel of ['hud', 'events', 'driver-analysis', 'shift-light', 'garage', 'settings']) {
    const intros = header.match(new RegExp(`<p data-settings-intro="${panel}"( hidden)?>[^<]+</p>`, 'g')) || []
    assert.equal(intros.length, 1, panel)
    const start = settingsHtml.indexOf(`data-settings-panel="${panel}"`)
    const next = settingsHtml.indexOf('data-settings-panel="', start + 1)
    const markup = settingsHtml.slice(start, next === -1 ? undefined : next)
    assert.doesNotMatch(markup, /data-settings-intro/, panel)
  }
  // Only the active tab's intro shows; drill-down views hide it with the compact header.
  assert.match(settingsHtml, /<p data-settings-intro="hud">/)
  assert.match(settingsJs, /for \(const intro of settingsIntros\) intro\.hidden = intro\.dataset\.settingsIntro !== tabName/)
  assert.match(settingsCss, /:is\(\.events-detail-view, \.events-run-view, \.driver-analysis-detail-view\):not\(\[hidden\]\)\)\s*\.settings-header__intro\s*\{\s*display: none;/)
  assert.match(settingsHtml, /<h2 id="settings-panel-title" class="settings-page-title">SETTINGS<\/h2>/)
  assert.match(settingsHtml, /<p data-settings-intro="settings" hidden>Options for the whole app\. Everything FDC records stays on this PC\.<\/p>/)
  assert.doesNotMatch(settingsHtml, /YOUR DATA/)
  assert.doesNotMatch(settingsHtml, /VISUAL OUTPUT|RECORDED ASPHALT REVIEW|VEHICLE LIBRARY|AUTO CALIBRATION/)
})

test('Configuration exposes Events second and Driver Analysis third in the primary tab order', () => {
  const tabs = [...settingsHtml.matchAll(/data-settings-tab="([^"]+)"/g)].map(match => match[1])

  assert.deepEqual(tabs, ['hud', 'events', 'driver-analysis', 'shift-light', 'garage', 'settings'])
  assert.match(settingsHtml, /id="driver-analysis-panel"[^>]+data-settings-panel="driver-analysis"/)
  assert.match(settingsHtml, /id="driver-analysis-enabled"[^>]+aria-pressed="false"/)
  assert.match(settingsHtml, /id="driver-analysis-record"[^>]+disabled>RECORD<\/button>/)
  assert.match(settingsHtml, /id="driver-analysis-hotkey-value"[^>]*>Ctrl \+ Shift \+ F9<\/output>/)
  assert.match(settingsHtml, /<strong>BETA<\/strong>/)
  assert.match(settingsHtml, /Experimental — results may be inaccurate\. Asphalt only\./)
  assert.match(settingsHtml, /id="driver-analysis-history-list"[^>]+aria-live="polite"/)
  assert.match(settingsJs, /call\('load_driver_analysis_sessions'\)/)
  assert.match(settingsJs, /call\('delete_driver_analysis_recording', \{ recordingId[\s\S]*\}\)/)
  assert.match(settingsJs, /Delete this Driver Analysis recording, all its cars, and saved telemetry\?/)
  assert.match(settingsJs, /phase === 'waiting'/)
  assert.match(settingsJs, /phase === 'finalizing'/)
  assert.doesNotMatch(settingsHtml, /Driver Coach|data-layout-target="coach"/)
  assert.doesNotMatch(overlayHtml, /id="coach-card"|id="coachbar"/)
  assert.doesNotMatch(overlayHtml, /asphalt-coach|driver-coach|coach-layout/)
  assert.match(settingsHtml, /id="garage-panel"[^>]+data-settings-panel="garage"/)
  assert.match(settingsHtml, /id="garage-grid"[^>]+aria-live="polite"/)
  assert.match(settingsHtml, /id="garage-current-car"/)
  assert.match(settingsHtml, /id="garage-current-variants-toggle"[^>]*>VIEW<\/button>/)
  assert.match(settingsHtml, /id="garage-current-variants"[^>]+class="garage-variants"/)
  assert.match(settingsHtml, /id="garage-cars-count">0 CARS/)
  assert.doesNotMatch(settingsHtml, /ONE CARD PER CAR ORDINAL/)
  assert.doesNotMatch(settingsHtml, /garage-current-title[^]*LAST USED/)
  assert.match(settingsJs, /load_garage_snapshot/)
  assert.match(settingsJs, /rename_garage_car/)
  assert.match(settingsJs, /garage-current-car__input/)
  assert.match(settingsJs, /garage-performance--/)
  assert.match(settingsJs, /garage-current-car__group/)
  assert.match(settingsJs, /garage-current-car__drivetrain/)
  assert.match(settingsJs, /garage-current-car__cylinders/)
  assert.match(settingsJs, /details\.append\(garageCurrentVariantsToggle\)/)
  assert.match(settingsJs, /garageVariantsFor/)
  assert.match(settingsJs, /garage-variant-row__cylinders/)
  assert.match(settingsJs, /\?\? vehicle\?\.cylinders/)
  assert.match(settingsJs, /garage-current-variants-toggle/)
  assert.match(settingsJs, /garageCurrentVariantsToggle\?\.addEventListener\('click', toggleGarageVariants\)/)
  assert.match(settingsJs, /event\.key !== 'Escape'/)
  assert.match(settingsJs, /garage-current-car__input/)
  assert.doesNotMatch(settingsJs, /garage-shift-light/)
  assert.doesNotMatch(settingsJs, /Duplicate/u)
  assert.doesNotMatch(settingsJs, /appendGarageShiftLight/)
  assert.match(settingsJs, /garage-card--latest/)
  assert.match(settingsJs, /latest\.textContent = 'LAST USED'/)
  assert.doesNotMatch(settingsJs, /input\.className = 'garage-card__name'/)
  assert.match(settingsCss, /\.garage-variants\s*\{[\s\S]*grid-auto-rows:\s*36px[\s\S]*max-height:\s*432px[\s\S]*overflow-y:\s*auto/)
  assert.match(settingsCss, /\.garage-variants\s*\{[\s\S]*width:\s*100%[\s\S]*border:\s*1px solid/)
  assert.match(settingsCss, /\.garage-variant-row\s*\{[\s\S]*justify-content:\s*flex-start/)
  assert.match(settingsCss, /\.garage-variant-row\s*\{[\s\S]*border-left:\s*3px solid var\(--garage-rank-color\)/)
  assert.doesNotMatch(settingsCss, /\.garage-current-variants-toggle\s*\{[^}]*position:\s*absolute/)
  assert.match(settingsCss, /\.garage-current-variants-toggle\s*\{[\s\S]*margin-left:\s*auto/)
})

test('Events keeps the existing navigation and exposes the create/detail flow', () => {
  assert.match(settingsHtml, /id="events-tab"[^>]+data-settings-tab="events"/)
  assert.match(settingsHtml, /id="events-panel"[^>]+data-settings-panel="events"/)
  assert.match(settingsHtml, /id="events-grid"[^>]+aria-live="polite"/)
  assert.match(settingsHtml, /id="events-create-toggle"[^>]+aria-controls="events-create-area"/)
  assert.match(settingsHtml, /id="events-create-area"[^>]+hidden/)
  assert.ok(settingsHtml.indexOf('id="events-create-area"') < settingsHtml.indexOf('id="events-grid"'))
  assert.match(settingsHtml, /id="events-discard-dialog"[^>]+role="alertdialog"[^>]+hidden/)
  assert.match(settingsHtml, /id="events-discard-yes"[^>]*>YES<\/button>/)
  assert.match(settingsHtml, /id="events-discard-no"[^>]*>NO<\/button>/)
  for (const id of ['event-name', 'event-class', 'event-route-type', 'event-mode', 'event-notes']) {
    assert.match(settingsHtml, new RegExp(`id="${id}"`))
  }
  const formStart = settingsHtml.indexOf('id="events-create-form"')
  const formEnd = settingsHtml.indexOf('</form>', formStart)
  const eventsForm = settingsHtml.slice(formStart, formEnd)
  assert.ok(eventsForm.indexOf('id="event-name"') < eventsForm.indexOf('id="event-mode"'))
  assert.ok(eventsForm.indexOf('id="event-mode"') < eventsForm.indexOf('id="event-route-type"'))
  assert.ok(eventsForm.indexOf('id="event-route-type"') < eventsForm.indexOf('id="event-class"'))
  assert.ok(eventsForm.indexOf('id="event-class"') < eventsForm.indexOf('id="event-notes"'))
  assert.match(settingsHtml, /id="events-detail-view"[^>]+hidden/)
  assert.match(settingsHtml, /id="events-detail-back"[^>]*class="detail-back"[^>]*>← EVENTS<\/button>/)
  assert.match(settingsHtml, /id="events-detail-title"/)
  assert.match(settingsHtml, /id="events-detail-summary"[^>]+aria-label="Event details"/)
  assert.match(settingsHtml, /id="events-detail-notes"[^>]+hidden/)
  assert.match(settingsHtml, /id="events-detail-absolute-best"/)
  assert.doesNotMatch(settingsHtml, /id="events-detail-hint"|id="events-detail-card"|id="events-detail-metadata"/)
  assert.doesNotMatch(settingsHtml, /id="events-detail-archive"/)
  assert.match(settingsHtml, /id="events-detail-delete"/)
  assert.match(settingsHtml, /id="events-run-view"[^>]+hidden/)
  assert.match(settingsHtml, /id="events-run-back"[^>]*class="detail-back"[^>]*>← EVENT<\/button>/)
  assert.match(settingsHtml, /id="events-run-title"/)
  assert.match(settingsHtml, /id="events-run-summary"[^>]+aria-label="Event details"/)
  assert.match(settingsHtml, /id="events-run-bht"/)
  assert.match(settingsHtml, /id="events-run-lap-sort"[^>]+aria-sort="descending"/)
  assert.match(settingsHtml, /id="events-run-laps"/)
  assert.match(settingsJs, /call\('create_event', payload\)/)
  assert.match(settingsJs, /route: eventRouteType\.value/)
  assert.match(settingsJs, /call\('load_events'\)/)
  assert.match(settingsJs, /call\('load_event'/)
  assert.match(settingsJs, /call\('rename_event'/)
  assert.match(settingsJs, /function nativeEventId\(value\)/)
  assert.match(settingsJs, /call\('rename_event', \{ eventId: nativeEventId\(event\.id\), name \}\)/)
  assert.doesNotMatch(settingsJs, /archive_event|archiveCurrentEvent|archived_at/)
  assert.match(settingsJs, /call\('delete_event'/)
  assert.match(settingsJs, /call\('delete_event', \{ eventId: nativeEventId\(event\.id\) \}\)/)
  assert.match(settingsJs, /await confirmDestructive\(`Delete event/)
  assert.match(settingsJs, /await confirmDestructive\('Reset the calibration of the current car\?/)
  assert.match(settingsJs, /latestShiftLightState\?\.carKey !== carKey[\s\S]*CALIBRATION NOT RESET/)
  assert.match(settingsJs, /function eventCreateFormHasContent\(\)/)
  assert.match(settingsJs, /function requestEventsCreateClose\(\)/)
  assert.match(settingsJs, /if \(eventsView === 'library' && eventsCreateOpen\)/)
  assert.match(settingsJs, /events-detail-view__title-input/)
  assert.match(settingsJs, /events-detail-view__badge--mode/)
  assert.match(settingsJs, /events-detail-view__badge--class/)
  assert.match(settingsJs, /eventsDetailNotes\.hidden = !event\.notes/)
  assert.doesNotMatch(settingsJs, /function renderEventDetail\([^]*renderEventCard\(event, true\)/)
  assert.match(settingsJs, /id\.textContent = `#\$\{event\.id\}`/)
  assert.match(settingsJs, /call\('load_event_absolute_best', \{ eventId: nativeEventId \}\)/)
  assert.match(settingsJs, /eventsDetailAbsoluteBest\.textContent = formatRunTime\(currentEventAbsoluteBestMs\)/)
  assert.doesNotMatch(settingsJs, /events-card__image/)
  assert.doesNotMatch(settingsJs, /copyEventId|events-card__copy/)
  assert.match(settingsJs, /eventsView === 'detail'/)
  assert.match(settingsJs, /function openEventRun\(id\)/)
  assert.match(settingsJs, /function closeEventRun\(\)/)
  assert.match(settingsJs, /function runBestHypotheticalTimeMs\(run\)/)
  assert.match(settingsJs, /function savedRunTimeLabel\(run\)/)
  assert.match(settingsJs, /RESULT \$\{formatRunTime\(run\.finalTimeMs\)\}/)
  assert.match(settingsJs, /LAST \$\{formatRunTime\(lap\.timeMs\)\}/)
  assert.match(settingsJs, /eventRunLapSortDirection = 'desc'/)
  assert.match(settingsJs, /value\.dataset\.tone = tone/)
  assert.match(settingsCss, /\.settings-tabs\s*\{[\s\S]*grid-template-columns:\s*repeat\(6,/)
  assert.match(settingsCss, /\.events-grid\s*\{[\s\S]*grid-template-columns:\s*repeat\(auto-fit/)
  assert.match(settingsCss, /\.events-card__id\s*\{[\s\S]*font-size:\s*28px/)
  assert.match(settingsStyles, /\.confirm-dialog \.confirm-dialog__no\s*\{[^}]*background:\s*var\(--accent\)/)
  assert.match(settingsStyles, /\.confirm-dialog \.settings-button\.confirm-dialog__yes:not\(:disabled\):hover[^{]*\{[^}]*background:\s*var\(--danger\)/)
  assert.doesNotMatch(settingsCss, /events-card__image/)
  assert.doesNotMatch(settingsCss, /events-card__copy/)
  assert.match(settingsCss, /\.events-card\[data-event-mode="any"\][\s\S]*#f97316/)
  assert.match(settingsCss, /\.events-card\[data-event-mode="rivals"\][\s\S]*#7dd3fc/)
  assert.match(settingsCss, /\.events-card\[data-event-mode="online"\][\s\S]*#facc15/)
  assert.match(settingsCss, /\.events-card\[data-event-mode="eventlab"\][\s\S]*#ffffff/)
  assert.match(settingsCss, /\.events-card\[data-event-mode="official"\][\s\S]*#ef4444/)
  assert.match(settingsCss, /\.events-card\[data-event-mode="blueprint"\][\s\S]*#c084fc/)
  assert.match(settingsJs, /events-card__badge--class/)
  assert.match(settingsJs, /meta\.append\(mode, route, eventClass\)/)
  assert.match(settingsCss, /\.events-card__badge--class\[data-event-class="B"\][\s\S]*#f97316/)
  assert.match(settingsCss, /\.events-detail-view__badge--class\[data-event-class="A"\][\s\S]*#ef4444/)
  assert.match(settingsCss, /\.events-detail-view__badge--class\[data-event-class="S1"\][\s\S]*#c084fc/)
  assert.match(settingsStyles, /\.events-run-table__time\[data-tone="best"\]\s*\{[^}]*var\(--best\)/)
  assert.match(settingsStyles, /\.events-run-table__time\[data-tone="second"\]\s*\{[^}]*var\(--accent\)/)
  assert.match(settingsStyles, /\.events-detail-view__absolute-best-value\s*\{[^}]*var\(--best\)/)
})

test('Event recorder uses the compact idle control and local run timestamps', () => {
  assert.doesNotMatch(settingsHtml, /event-recorder__eyebrow|RUN CAPTURE/)
  assert.match(settingsHtml, /id="event-recorder-status"[^>]+hidden/)
  assert.match(settingsHtml, /id="event-recorder-toggle"[^>]*>RECORD RUN<\/button>/)
  assert.match(settingsJs, /eventRecorderStatus\.hidden = !recording && !finalizing/)
  assert.match(settingsJs, /eventRecorderToggle\.textContent = finalizing \? 'FINALIZING' : recording \? 'STOP' : 'RECORD RUN'/)
  assert.match(settingsJs, /eventRecorderToggle\.disabled = recordingAnotherEvent \|\| finalizing/)
  assert.match(settingsHtml, /data-tone="warning"[^>]*>Sprint: keep recording armed between attempts, then press STOP\.<\/p>/)
  assert.match(settingsJs, /Sprint: keep recording armed between attempts, then press STOP\./)
  assert.match(settingsJs, /eventRecorderHint\.dataset\.tone = !recordingAnotherEvent && !finalizing \? 'warning' : ''/)
  assert.match(settingsStyles, /\.event-recorder__hint\[data-tone="warning"\]\s*\{[^}]*var\(--notice\)/)
  assert.match(settingsJs, /getHours\(\).*getMinutes\(\).*getSeconds\(\)/s)
  assert.match(settingsStyles, /\.event-recorder\s*\{[^}]*border: 1px solid var\(--line-strong\);[^}]*background: var\(--panel\)/)
  assert.match(settingsStyles, /\.event-recorder__record\s*\{[^}]*background: var\(--accent\)/)
  assert.match(settingsStyles, /\.settings-button--danger\s*\{[^}]*color: var\(--danger-text\)/)
})

test('Events expose deterministic persisted list sorting and in-memory run sorting', () => {
  assert.match(settingsHtml, /id="events-sort"[^>]+aria-label="Sort events"/)
  assert.deepEqual(
    [...settingsHtml.matchAll(/<option value="([^"]+)">/g)].map(match => match[1]).filter(value => value.includes('recorded') || value.startsWith('id-')),
    ['id-desc', 'id-asc', 'last-recorded-desc', 'last-recorded-asc']
  )
  assert.match(settingsJs, /const EVENTS_SORT_STORAGE_KEY = 'fdc\.events-sort\.v1'/)
  assert.match(settingsJs, /localStorage\.setItem\(EVENTS_SORT_STORAGE_KEY, JSON\.stringify\(value\)\)/)
  assert.match(settingsJs, /let eventRunsSort = \{ key: 'date', direction: 'desc' \}/)
  assert.match(settingsHtml, /data-run-sort="id"/)
  assert.match(settingsHtml, /data-run-sort="best"/)
  assert.match(settingsHtml, /<span class="event-run-row__header-label">LAPS<\/span>/)
  assert.match(settingsHtml, /data-run-sort="date"/)
  const bestHeader = settingsHtml.indexOf('data-run-sort="best"')
  const lapsHeader = settingsHtml.indexOf('event-run-row__header-label">LAPS')
  const dateHeader = settingsHtml.indexOf('data-run-sort="date"')
  assert.ok(bestHeader < lapsHeader && lapsHeader < dateHeader)
  assert.match(settingsJs, /const lapCount = run\.laps\.length/)
  assert.match(settingsJs, /\['LAPS', lapCount\]/)
  assert.match(settingsJs, /Open run \$\{run\.id\}, \$\{lapCount\} \$\{lapCount === 1 \? 'lap' : 'laps'\}/)
  assert.match(settingsJs, /run\?\.runType === 'sprint'/)
  assert.match(settingsJs, /applyEventRunDates\(normalizeEventRunsPayload\(await call\('load_event_runs'/)
})

test('Event lap rows expose trace details and time-weighted pedal statistics', () => {
  assert.match(settingsHtml, /events-run-table__caption[^>]*>Select a lap row to view its trace and pedal statistics\.<\/caption>/)
  assert.match(settingsJs, /function normalizeTracePoints\(value\)/)
  assert.doesNotMatch(settingsJs, /TRACE · X \/ Z/)
  assert.match(settingsJs, /const positionX = finiteNumber/)
  assert.match(settingsJs, /const positionZ = finiteNumber/)
  assert.match(settingsJs, /function traceStats\(points/)
  assert.match(settingsJs, /totals\[traceState\(points\[index\]\)\] \+= elapsed/)
  assert.match(settingsJs, /const remaining = Number\.isFinite\(lapTimeMs\)/)
  assert.match(settingsJs, /totals\[traceState\(points\.at\(-1\)\)\] \+= remaining/)
  assert.match(settingsJs, /if \(normalizePedal\(point\?\.brake\) >= 0\.05\) return 'brake'/)
  assert.match(settingsJs, /events-lap-detail__trace events-lap-detail__trace--\$\{pedal\}/)
  assert.match(settingsJs, /traceMapLayerSelection/)
  assert.match(settingsJs, /globalThis\.EventTraceMap\?\.nextLayerSelection/)
  assert.match(settingsJs, /detail\.append\(renderTraceMap\(lap\.tracePoints \|\| \[\], lap\.timeMs\)\)/)
  assert.doesNotMatch(settingsJs, /function renderTraceStats/)
  assert.match(settingsJs, /globalThis\.EventTraceMap\?\.pedalState/)
  assert.match(settingsJs, /globalThis\.EventTraceMap\?\.groupRuns/)
  assert.match(settingsJs, /events-lap-detail__sector-tick/)
  assert.match(settingsJs, /events-lap-detail__stat--\$\{key\}/)
  assert.match(settingsJs, /if \(expandedEventRunLap !== null\)/)
  assert.match(settingsJs, /row\.setAttribute\('aria-expanded', String\(expanded\)\)/)
  assert.match(settingsJs, /call\('load_event_run', \{ runId: nativeRunId \}\)/)
  assert.match(settingsCss, /\.events-lap-detail\s*\{[\s\S]*grid-template-columns: minmax\(0, 1fr\);/)
  assert.match(settingsCss, /\.events-lap-detail__trace\s*\{[\s\S]*stroke-width: 2\.4;/)
  assert.match(settingsCss, /\.events-lap-detail__trace--throttle\s*\{\s*stroke: #69e83f;/)
  assert.match(settingsCss, /\.events-lap-detail__trace--brake\s*\{\s*stroke: #ef4444;/)
  assert.match(settingsCss, /\.events-lap-detail__trace--coast\s*\{\s*stroke: #facc15;/)
  assert.match(settingsStyles, /\.events-lap-detail__sector-tick\s*\{\s*stroke: var\(--text\);/)
  assert.match(settingsStyles, /\.events-lap-detail__sector-label\s*\{\s*fill: var\(--text\);/)
  assert.match(settingsCss, /\.events-lap-detail__legend\s*\{/)
  assert.match(settingsCss, /\.events-lap-detail__svg\s*\{[\s\S]*max-height: 560px;/)
  assert.match(settingsCss, /\.events-lap-detail__tooltip/)
  assert.doesNotMatch(settingsJs, /events-lap-detail__stat-key/)
  assert.match(settingsCss, /\.events-run-view__metric\s*\{[\s\S]*align-items: center;/)
})

test('Engine telemetry keeps the compact panel order and one visibility toggle', () => {
  const sections = [...overlayHtml.matchAll(/<section id="(hud-[^"]+)"/g)].map(match => match[1])
  const components = [...settingsHtml.matchAll(/data-hud-toggle="([^"]+)"/g)].map(match => match[1])

  assert.deepEqual(sections, ['hud-tires', 'hud-pedals', 'hud-steering', 'hud-gear', 'hud-engine', 'hud-history'])
  assert.deepEqual(components, ['tires', 'pedals', 'steering', 'gear', 'engine', 'history'])
  assert.match(settingsHtml, /<span class="widget-row__name">Engine \/ Boost<\/span>/)
  assert.match(overlayHtml, /id="engine-boost"[^>]+aria-label="Boost pressure"/)
  assert.match(overlayHtml, /id="engine-power"[^>]+aria-label="Engine power"/)
  assert.match(overlayHtml, /id="engine-torque"[^>]+aria-label="Engine torque"/)
})

test('Engine visibility is part of the safe HUD component contract', () => {
  const hudWidgets = require('./hud-widgets.js')

  assert.deepEqual(hudWidgets.COMPONENTS, ['tires', 'pedals', 'steering', 'gear', 'engine', 'history'])
  assert.equal(hudWidgets.COLUMN_WIDTHS.engine, 116)
  assert.match(tauriMain, /"tires" \| "pedals" \| "steering" \| "gear" \| "engine" \| "history"/)
})

test('HUD layout exposes grouped and freeform modes with unified widgets and layout editing', () => {
  // The layout plate has three sections in order: ARRANGEMENT, LAYOUT, WIDGETS.
  // Three blocks in order: the ARRANGEMENT card, the layout editor (an action panel like the
  // Driver Analysis recorder), and the WIDGETS card.
  assert.match(settingsHtml, /<section class="shift-light-brightness-card layout-arrangement" aria-labelledby="hud-layout-arrangement-title">[\s\S]*?<h3 id="hud-layout-arrangement-title">ARRANGEMENT<\/h3>[\s\S]*?class="unit-options" role="radiogroup" aria-labelledby="hud-layout-arrangement-title"[\s\S]*?<\/section>\s*<section class="action-panel"[^>]*data-layout-edit-row>[\s\S]*?<h3 id="hud-layout-edit-title">EDIT THE LAYOUT<\/h3>[\s\S]*?<strong>IN-GAME EDIT HOTKEY<\/strong>[\s\S]*?<\/section>\s*<section class="layout-list" aria-labelledby="hud-widgets-title">[\s\S]*?id="hud-widgets-title" class="layout-section__title">WIDGETS</)
  // The editor shows EDITING while an edit runs, like READY on the Driver Analysis recorder.
  assert.match(settingsHtml, /id="hud-layout-status" class="action-panel__status" data-state="editing" role="status" aria-live="polite" hidden>EDITING</)
  assert.match(settingsJs, /if \(status\) status\.hidden = !editing/)
  assert.match(settingsStyles, /\.driver-analysis-recorder__main,\s*\.driver-analysis-hotkey,\s*\.action-panel__row \{/)
  assert.match(settingsStyles, /\.action-panel__status\[data-state='editing'\] \{\s*color: var\(--warning\);/)
  // Widgets are compact rows with a name only; the whole row toggles its widget.
  assert.equal(settingsHtml.match(/<label class="widget-row">\s*<span class="widget-row__name">[^<]+<\/span>\s*<button class="visibility-toggle"/g)?.length, 7)
  assert.doesNotMatch(settingsHtml, /layout-row|visibility-row/)
  assert.doesNotMatch(settingsHtml, /data-freeform-layout-list|data-grouped-layout-row/)
  assert.match(settingsHtml, /data-layout-mode="grouped" checked/)
  assert.match(settingsHtml, /data-layout-mode="freeform"/)

  // Layout edit row has EDIT LAYOUT, RESET LAYOUT, SAVE, CANCEL
  assert.match(settingsHtml, /id="hud-layout-edit"[^>]*class="settings-button settings-button--ready"/)
  assert.match(settingsHtml, /id="hud-layout-reset"[^>]*class="settings-button settings-button--caution"/)
  assert.match(settingsHtml, /id="hud-layout-save"/)
  assert.match(settingsHtml, /id="hud-layout-cancel"/)
  assert.match(settingsHtml, /data-layout-edit-row/)

  // One widget list with all widgets and ALL toggle

  assert.match(settingsHtml, /id="hud-all-widgets"[^>]*data-hud-toggle-all/)
  for (const component of ['tires', 'pedals', 'steering', 'gear', 'engine', 'history']) {
    assert.match(settingsHtml, new RegExp(`data-hud-toggle="${component}"`, 'u'))
  }
  assert.match(settingsHtml, /data-overlay-toggle="delta"/)

  // No old per-row edit buttons or accordion
  assert.doesNotMatch(settingsHtml, /data-layout-action="edit"|data-accordion-toggle|visibility-list/)

  // Native contract for layout actions
  assert.match(settingsJs, /call\('layout_action', \{ action: 'start', target: 'hud' \}\)/)
  assert.match(settingsJs, /call\('layout_action', \{ action: 'reset_all', target: 'hud' \}\)/)
  assert.match(settingsJs, /const LAYOUT_MODE_STORAGE_KEY = 'fdc\.layout-mode\.v1'/)
  assert.match(settingsJs, /call\('set_layout_mode', \{ mode: nextMode \}\)/)
  assert.match(tauriMain, /fn set_layout_mode\(app: AppHandle, mode: String\)/)
})

test('the header status opens the connection guide instead of a permanent setup card', () => {
  const header = settingsHtml.slice(settingsHtml.indexOf('<header class="settings-header">'), settingsHtml.indexOf('</header>'))
  assert.match(header, /class="settings-header__connection"[\s\S]*<button id="telemetry-status-button"[^>]*type="button"[\s\S]*id="telemetry-status"[^>]*role="status"/)
  assert.doesNotMatch(settingsHtml, /telemetry-route-card|telemetry-setup-guide|telemetry-route-retry|HOW TO CONNECT/)
  assert.doesNotMatch(settingsJs, /telemetryRouteCard|telemetryRouteRetry/)
  assert.match(settingsJs, /telemetryStatusButton\?\.addEventListener\('click', openConnectionGuide\)/)
  assert.match(settingsJs, /function openConnectionGuide\(\) \{[\s\S]*?connectionGuideOpen = true[\s\S]*?renderConnectionGuide\(\)/)
  // The guide keeps the steps and RETRY DATA OUT for a receiver problem.
  const guide = settingsHtml.slice(settingsHtml.indexOf('class="connect-guide"'), settingsHtml.indexOf('id="connect-guide-done"'))
  assert.match(guide, /Data Out IP Address[\s\S]*127\.0\.0\.1/)
  assert.match(guide, /Data Out IP Port[\s\S]*5301/)
  assert.match(guide, /id="connect-guide-retry"/)
  assert.doesNotMatch(settingsHtml, /id="telemetry-route-endpoint"|id="telemetry-route-label"/)
  assert.doesNotMatch(settingsJs, /telemetryRouteEndpoint|telemetryRouteLabel|telemetryRouteDetail|telemetryRouteWarning/u)
  assert.doesNotMatch(overlayHtml, /telemetry-route-badge/)
})

test('Configuration title sits directly below the product name', () => {
  assert.match(settingsHtml, /class="settings-header__brand"[\s\S]*Feedback-Driven Companion[\s\S]*<h1 id="settings-title">CONFIGURATION<\/h1>/u)
  assert.doesNotMatch(settingsHtml, /Configure the overlay and Shift Light\./u)
})

test('Configuration heading follows the active tab', () => {
  assert.match(settingsJs, /const settingsTitle = document\.getElementById\('settings-title'\)/)
  assert.match(settingsJs, /const activeTab = settingsTabs\.find\(tab => tab\.dataset\.settingsTab === tabName\)/)
  assert.match(settingsJs, /settingsTitle\.textContent = activeTab\?\.textContent\.trim\(\) \|\| context/)
  assert.match(settingsJs, /function selectSettingsTab\(tabName\)/)
})

test('Configuration window title reflects the active section and build version without game branding', () => {
  const configuredTitles = JSON.parse(tauriConfig).app.windows.map(window => window.title)

  assert.deepEqual(
    [...settingsHtml.matchAll(/data-settings-tab="([^"]+)"/g)].map(match => match[1]),
    ['hud', 'events', 'driver-analysis', 'shift-light', 'garage', 'settings']
  )
  assert.deepEqual(configuredTitles, ['FDC · HUD', 'FDC · HUD'])
  assert.doesNotMatch(`${configuredTitles.join(' ')} ${overlayHtml}`, /Forza Horizon 6 HUD/u)
  assert.match(settingsJs, /const SETTINGS_WINDOW_CONTEXTS = Object\.freeze\(/)
  assert.match(settingsJs, /call\('set_settings_window_context', \{ context: tabName \}\)/)
  assert.match(tauriMain, /fn settings_window_context_label\(context: &str\) -> Option<&'static str>/)
  assert.match(tauriMain, /"hud" => Some\("HUD"\)/)
  assert.match(tauriMain, /"driver-analysis" => Some\("DRIVER ANALYSIS"\)/)
  assert.match(tauriMain, /"garage" => Some\("GARAGE"\)/)
  assert.match(tauriMain, /"events" => Some\("EVENTS"\)/)
  assert.match(tauriMain, /"shift-light" => Some\("SHIFT LIGHT"\)/)
  assert.match(tauriMain, /"settings" => Some\("SETTINGS"\)/)
  assert.match(tauriMain, /fn settings_window_title\(context: &str\) -> String/)
  assert.match(tauriMain, /format!\("FDC · \{context\} · v\{\}", get_app_version\(\)\)/)
  assert.match(tauriMain, /fn set_settings_window_context\(app: AppHandle, context: String\)/)
})

test('Configuration exposes only the Direct Data Out receiver', () => {
  assert.match(settingsHtml, /DIRECT DATA OUT/)
  assert.match(settingsHtml, /127\.0\.0\.1/)
  assert.match(settingsHtml, /5301/)
  assert.doesNotMatch(settingsHtml, /telemetry-source|co-driver|Suite|WebSocket/u)
  assert.doesNotMatch(settingsJs, /HudConnection|set_telemetry_source|selectTelemetrySource/u)
  assert.match(settingsJs, /call\('retry_direct_source'\)/u)
  assert.match(tauriMain, /fn retry_direct_source/u)
})

test('Settings exposes Configuration priority and speed unit preferences', () => {
  const settingsPanelIndex = settingsHtml.indexOf('id="settings-panel"')
  const displayPreferencesScriptIndex = settingsHtml.indexOf('src="display-preferences.js"')
  const settingsScriptIndex = settingsHtml.indexOf('src="settings.js"')
  const settingsPanel = settingsHtml.slice(settingsPanelIndex)

  assert.ok(settingsPanelIndex >= 0)
  assert.match(settingsHtml, /<section class="display-settings" aria-label="Display settings">/)
  assert.doesNotMatch(settingsHtml, /DISPLAY SETTINGS|WINDOW \+ SPEED FORMAT/u)
  assert.match(settingsHtml, /name="speed-unit" value="kmh"/)
  assert.match(settingsHtml, /name="speed-unit" value="mph"/)
  assert.match(settingsHtml, /name="distance-unit" value="km"/)
  assert.match(settingsHtml, /name="distance-unit" value="mi"/)
  assert.ok(settingsHtml.indexOf('speed-unit') < settingsHtml.indexOf('distance-unit'))
  assert.match(settingsHtml, /id="configuration-always-on-top" class="visibility-toggle" type="button"[^>]*aria-pressed="false"/)
  assert.match(settingsHtml, /<strong>SHOW HUD WITH TELEMETRY<\/strong>/)
  assert.match(settingsHtml, /id="show-hud-with-telemetry" class="visibility-toggle" type="button"[^>]*aria-pressed="true"/)
  assert.ok(settingsHtml.indexOf('id="show-hud-with-telemetry"') > settingsPanelIndex)
  assert.match(settingsJs, /showHudWithTelemetry/)
  assert.match(settingsHtml, /calibration-label">CLASS<\/span>\s*<output id="shift-light-car-pi">/)
  assert.match(settingsJs, /shiftLightCarKey\.textContent = FdcVehicle\.displayName\(garageVehicle\?\.name, state\.carOrdinal\)/)
  assert.match(settingsJs, /state\.carKey\.split\(':'\)\[2\]/)
  assert.match(settingsJs, /appendGaragePerformance\(shiftLightCarPi, \{ classLabel, pi \}\)/)
  assert.match(settingsJs, /set_configuration_always_on_top/)
  assert.match(tauriMain, /fn set_configuration_always_on_top/)
  assert.doesNotMatch(settingsPanel, /telemetry-settings|telemetry-route-card|DIRECT DATA OUT.*OFFLINE/u)
  assert.ok(displayPreferencesScriptIndex >= 0)
  assert.ok(settingsScriptIndex > displayPreferencesScriptIndex)
})

test('Shift Light exposes separate redline and FDC cue controls in the Shift Light tab', () => {
  const shiftLightPanelIndex = settingsHtml.indexOf('id="shift-light-panel"')
  const redlineIndex = settingsHtml.indexOf('id="redline-brightness"')
  const redlineResetIndex = settingsHtml.indexOf('id="redline-brightness-reset"')
  const cueToggleIndex = settingsHtml.indexOf('id="fdc-shift-light-enabled"')
  const brightnessIndex = settingsHtml.indexOf('id="shift-light-brightness"')
  const settingsPanelIndex = settingsHtml.indexOf('id="settings-panel"')

  assert.ok(shiftLightPanelIndex >= 0)
  assert.ok(redlineIndex > shiftLightPanelIndex)
  assert.ok(redlineResetIndex > shiftLightPanelIndex)
  assert.ok(cueToggleIndex > redlineResetIndex)
  assert.ok(brightnessIndex > shiftLightPanelIndex)
  assert.ok(brightnessIndex > cueToggleIndex)
  assert.ok(brightnessIndex < settingsPanelIndex)
  assert.match(settingsHtml, /<h3 id="redline-brightness-title">REDLINE BRIGHTNESS<\/h3>/)
  assert.match(settingsHtml, /id="redline-brightness-value"[^>]*>80%<\/output>/)
  assert.match(settingsHtml, /id="redline-brightness" type="range" min="0" max="100" step="5" value="80"/)
  assert.match(settingsHtml, /id="redline-brightness-reset"[^>]*type="button"[^>]*disabled>RESET<\/button>/)
  assert.match(settingsHtml, /id="fdc-shift-light-enabled" class="visibility-toggle" type="button"[^>]*aria-pressed="true"/)
  assert.doesNotMatch(settingsHtml, /class="brightness-scale"/)
  assert.match(settingsHtml, /<h3 id="shift-light-brightness-title">FDC SHIFT LIGHT BRIGHTNESS<\/h3>/)
  assert.match(settingsHtml, /class="shift-light-brightness-card"/)
  assert.match(settingsHtml, /id="shift-light-brightness" type="range" min="0" max="100" step="5" value="80"/)
  assert.match(settingsHtml, /<span class="calibration-label">LEARNED CEILING<\/span>/)
  assert.match(settingsHtml, /id="shift-light-usable-ceiling"/)
  assert.match(settingsHtml, /<dt>LEARNING<\/dt><dd>Shifts at the safe redline while FDC watches your full-throttle upshifts\.<\/dd>/)
  assert.match(settingsHtml, /<dt>POTENTIAL<\/dt>/)
  assert.match(settingsHtml, /Only clean full-throttle upshifts count; other shifts are ignored\./)
  assert.match(settingsJs, /redlineBrightness/)
  assert.match(settingsJs, /fdcShiftLightEnabled/)
})

test('HUD opacity appears before HUD controls and resets to its 80 percent default', () => {
  const hudOpacityIndex = settingsHtml.indexOf('id="hud-opacity"')
  const layoutListIndex = settingsHtml.indexOf('class="shift-light-brightness-card layout-arrangement"')

  assert.ok(hudOpacityIndex >= 0)
  assert.ok(hudOpacityIndex < layoutListIndex)
  assert.match(settingsHtml, /id="hud-opacity" type="range" min="1" max="100" step="1" value="80"/)
  assert.match(settingsHtml, /id="hud-opacity-reset" class="settings-button hud-opacity-reset" type="button" disabled>RESET<\/button>/)
  assert.match(settingsJs, /HUD OPACITY RESET TO \$\{next\.hudOpacity\}%/)
  assert.match(settingsJs, /hudOpacityReset\.disabled = pending \|\| displayPreferences\.hudOpacity === DEFAULT_HUD_OPACITY/)
  assert.match(settingsStyles, /\.hud-opacity-reset\.is-dirty:not\(:disabled\)\s*\{[^}]*var\(--caution\)/)
})

test('HUD heading has no redundant position and visibility label, and status uses a fixed footer', () => {
  assert.doesNotMatch(settingsHtml, /POSITION \+ VISIBILITY/)
  assert.match(settingsHtml, /<footer class="settings-footer"[^>]*aria-label="Configuration status"[^>]*>/)
  assert.match(settingsHtml, /id="settings-status"[^>]*role="status"/)
  assert.match(settingsHtml, /id="app-version"[^>]*type="button"[^>]*title="Click to copy"[^>]*disabled/)
  assert.match(settingsHtml, /id="settings-help-toggle"[^>]*type="button"[^>]*aria-haspopup="menu"[^>]*aria-expanded="false"[^>]*aria-controls="settings-help-menu">HELP<\/button>/)
  assert.match(settingsHtml, /id="settings-help-menu"[^>]*role="menu"[^>]*aria-labelledby="settings-help-toggle"[^>]*hidden>/)
  const menuItems = [...settingsHtml.matchAll(/data-feedback-link="([^"]+)"/g)].map(m => m[1])
  assert.deepEqual(menuItems, ['bug', 'idea', 'question'])
  assert.match(settingsHtml, /data-feedback-link="bug"[^>]*>Report a bug<\/button>/)
  assert.match(settingsHtml, /data-feedback-link="idea"[^>]*>Suggest an idea<\/button>/)
  assert.match(settingsHtml, /data-feedback-link="question"[^>]*>Ask a question<\/button>/)
  assert.doesNotMatch(settingsHtml, /v\d+\.\d+\.\d+/)
  assert.doesNotMatch(settingsJs, /v\d+\.\d+\.\d+/)
  assert.match(settingsJs, /getElementById\('settings-status'\)/)
  assert.match(settingsJs, /getElementById\('settings-help-toggle'\)/)
  assert.match(settingsJs, /getElementById\('settings-help-menu'\)/)
  assert.match(settingsJs, /call\('get_app_version'\)/)
  assert.match(settingsJs, /appVersionNumber = normalizedVersion/)
  assert.match(settingsJs, /appVersion\.textContent = `v\$\{normalizedVersion\}`/)
  assert.match(settingsJs, /appVersion\.disabled = false/)
  assert.match(settingsJs, /function copyAppVersionToClipboard\(\)/)
  assert.match(settingsJs, /navigator\.clipboard\.writeText/)
  assert.match(settingsJs, /document\.execCommand\('copy'\)/)
  assert.match(settingsJs, /COPIED/)
  assert.match(settingsJs, /call\('open_feedback_link', \{ kind \}\)/)
  assert.match(settingsJs, /toggleHelpMenu/)
  assert.match(settingsJs, /handleHelpMenuKeydown/)
  assert.match(tauriMain, /fn get_app_version\(\) -> &'static str/)
  assert.match(cargoManifest, /^version = "\d+\.\d+\.\d+"$/m)
  assert.equal(Object.hasOwn(JSON.parse(tauriConfig), 'version'), false)
  assert.match(settingsCss, /--settings-footer-height:\s*52px;/)
  assert.match(settingsStyles, /\.settings-shell\s*{[^}]*padding:[^;]*calc\([^;]*\+ var\(--settings-footer-height\)\);/)
  assert.match(settingsStyles, /\.settings-footer\s*{[\s\S]*?position:\s*fixed;[\s\S]*?height:\s*var\(--settings-footer-height\);[\s\S]*?border-top:[\s\S]*?background:\s*var\(--bg\);/)
  assert.match(settingsCss, /\.settings-footer__right\s*{[\s\S]*?margin-left:\s*auto/)
  assert.match(settingsCss, /\.settings-footer__version\s*{[\s\S]*?cursor:\s*pointer/)
  assert.match(settingsCss, /\.settings-footer__help\s*{[\s\S]*?font-weight:\s*800/)
  assert.match(settingsCss, /\.settings-help-menu\s*{[\s\S]*?position:\s*absolute/)
  assert.match(settingsCss, /\.settings-help-menu button\s*{[\s\S]*?width:\s*100%/)
  assert.doesNotMatch(settingsCss, /\.settings-status\s*{[^}]*position:\s*fixed;/)
})

test('Configuration persists and applies display preferences through the shared contract', () => {
  assert.match(settingsJs, /displayPreferencesApi\?\.read/)
  assert.match(settingsJs, /displayPreferencesApi\.normalize/)
  assert.match(settingsJs, /displayPreferencesApi\.write\(next\)/)
  assert.match(settingsJs, /call\('set_display_preferences', \{\s*speedUnit: next\.speedUnit,\s*redlineBrightness: next\.redlineBrightness,\s*shiftLightBrightness: next\.shiftLightBrightness,\s*hudOpacity: next\.hudOpacity,\s*fdcShiftLightEnabled: next\.fdcShiftLightEnabled,\s*showHudWithTelemetry: next\.showHudWithTelemetry\s*\}\)/)
  assert.match(settingsJs, /displayPreferences = previous\s*displayPreferencesApi\.write\(previous\)\s*renderDisplayPreferences\(previous\)/)
  assert.match(settingsJs, /redlineBrightness: DEFAULT_REDLINE_BRIGHTNESS/)
  assert.match(settingsJs, /fdcShiftLightEnabled: true/)
  assert.match(settingsJs, /showHudWithTelemetry: true/)
  assert.match(settingsJs, /configurationAlwaysOnTop: false/)
})

test('Configuration keeps its default size and exposes standard Windows controls', () => {
  const settingsWindow = JSON.parse(tauriConfig).app.windows.find(window => window.label === 'settings')

  assert.deepEqual({ width: settingsWindow.width, height: settingsWindow.height }, { width: 820, height: 620 })
  assert.equal(settingsWindow.minimizable, true)
  assert.equal(settingsWindow.maximizable, true)
  assert.equal(settingsWindow.alwaysOnTop, false)
})

test('Configuration restores its last on-screen position with its size', () => {
  assert.match(tauriMain, /SettingsWindowState/)
  assert.match(tauriMain, /WindowEvent::Resized\(_\) \| WindowEvent::Moved\(_\)/)
  assert.match(tauriMain, /window\.outer_position\(\)/)
  assert.match(tauriMain, /app\s*\.available_monitors\(\)/)
  assert.match(tauriMain, /window\.set_position\(position\)/)
  assert.match(tauriMain, /serde\(default\)/)
})

test('Configuration opens every time the HUD starts', () => {
  assert.match(tauriMain, /window\.show\(\)\?;\s*show_settings\(app\.handle\(\)\)\?;/)
  assert.doesNotMatch(tauriMain, /settings-first-launch-complete/)
})

test('tray has one Configuration action and no calibration reset action', () => {
  assert.match(tauriMain, /\.text\("settings", "Configuration"\)/)
  assert.doesNotMatch(tauriMain, /reset-shift/)
  assert.match(tauriMain, /\.text\("quit", "Quit"\)/)
})

test('the Configuration X button asks QUIT FDC? through the shared dialog', () => {
  assert.match(tauriMain, /CloseRequested[\s\S]*?prevent_close\(\)[\s\S]*?SettingsController\?\.requestQuit\?\.\(\)/)
  assert.match(tauriMain, /fn quit_app\(app: AppHandle\) \{\s*app\.exit\(0\);/)
  assert.doesNotMatch(tauriMain, /settings\.hide\(\)/)
  assert.ok(settingsHtml.indexOf('src="quit-confirmation.js"') < settingsHtml.indexOf('src="settings.js"'))
  assert.match(settingsHtml, /id="destructive-confirm-option" class="confirm-dialog__option" hidden/)
  assert.match(settingsHtml, /CONFIRM BEFORE QUITTING[\s\S]*?id="confirm-before-quit"/)
  assert.match(settingsJs, /title: 'QUIT FDC\?'[\s\S]*?yes: 'QUIT'[\s\S]*?no: 'CANCEL'/)
  assert.match(settingsJs, /driverAnalysisState\.recording === true \|\| recorderState\.recording === true/)
  assert.match(settingsJs, /call\('quit_app'\)/)
  assert.match(settingsJs, /globalScope\.SettingsController[\s\S]*requestQuit/)
})

test('Configuration opens on the connection guide until Forza first sends Data Out', () => {
  assert.ok(settingsHtml.indexOf('src="connection-guide.js"') < settingsHtml.indexOf('src="settings.js"'))
  const guide = settingsHtml.slice(settingsHtml.indexOf('id="connect-guide"'), settingsHtml.indexOf('id="destructive-confirm-dialog"'))
  assert.match(guide, /role="dialog" aria-modal="true"[^>]*hidden/)
  assert.match(guide, /Settings → HUD and Gameplay → Telemetry/)
  assert.match(guide, /<code class="connect-guide__value">127\.0\.0\.1<\/code>/)
  assert.match(guide, /<code class="connect-guide__value">5301<\/code>/)
  for (const id of ['connect-guide-retry', 'connect-guide-skip', 'connect-guide-done']) assert.match(guide, new RegExp('id="' + id + '"'))
  assert.match(settingsJs, /applyGaragePayload\(await call\('load_garage_snapshot'\)\)[\s\S]*?openConnectionGuideIfNeverConnected\(\)/)
  assert.match(settingsJs, /connectionGuideApi\.shouldShow\(connectionGuideApi\.read\(\), garageVehicles\.size > 0\)/)
  assert.match(settingsJs, /telemetryStatusLabel\.textContent = presentation\.statusLabel\s*renderConnectionGuide\(\)/)
  assert.match(settingsCss, /\.connect-guide \{[^}]*z-index: 15;/)
})

test('Configuration replays Shift Light state and waits for the real reset result', () => {
  assert.match(settingsJs, /hud_shift_light_reset_result/)
  assert.match(settingsJs, /call\('sync_shift_light_status'\)/)
  assert.equal(settingsJs.match(/CALIBRATION RESET COMPLETE/g)?.length, 1)
  assert.match(tauriMain, /fn sync_shift_light_status/)
})

test('Driver Analysis heading spacing does not affect toggle internals', () => {
  assert.match(settingsCss, /\.driver-analysis-heading > div > span\s*\{[\s\S]*?margin-top:\s*6px;/)
  assert.doesNotMatch(settingsCss, /\.driver-analysis-heading span\s*\{/)
})

test('Driver Analysis history cards open drill-down pages for recording, car, and drive', () => {
  assert.match(settingsHtml, /id="driver-analysis-history-view"[\s\S]*class="driver-analysis-history-view"/)
  assert.match(settingsHtml, /id="driver-analysis-detail-view"[\s\S]*class="driver-analysis-detail-view"/)
  assert.match(settingsHtml, /id="driver-analysis-detail-back"[\s\S]*class="detail-back"[\s\S]*><\/button>/)
  assert.match(settingsHtml, /id="driver-analysis-detail-title"[\s\S]*class="events-detail-view__title/)
  assert.match(settingsHtml, /id="driver-analysis-detail-summary"[\s\S]*class="events-detail-view__summary"/)
  assert.match(settingsHtml, /id="driver-analysis-detail-body"[\s\S]*class="driver-analysis-detail-view__body"/)
  assert.match(settingsJs, /let driverAnalysisView = \{ level: 'history'/)
  assert.match(settingsJs, /function setDriverAnalysisView/)
  assert.match(settingsJs, /function closeDriverAnalysisLevel/)
  assert.match(settingsJs, /function renderDriverAnalysisView/)
  assert.match(settingsJs, /function driverAnalysisHeadline/)
  assert.match(settingsJs, /const expandedDriverAnalysisStats = new Set\(\)/)
  assert.match(settingsJs, /driverAnalysisView\.level === 'history'/)
  assert.match(settingsJs, /driverAnalysisView\.level === 'recording'/)
  assert.match(settingsJs, /driverAnalysisView\.level === 'car'/)
  assert.match(settingsJs, /driverAnalysisView\.level === 'drive'/)
  assert.match(settingsJs, /recording\.sessions\.length === 1/)
  assert.match(settingsJs, /level: 'recording'/)
  assert.match(settingsJs, /level: 'car'/)
  assert.match(settingsJs, /level: 'drive'/)
  assert.match(settingsJs, /delete_driver_analysis_recording/)
  assert.match(settingsJs, /DriverAnalysisHistory\?.groupRecordings/)
  assert.match(settingsJs, /DriverAnalysisHistory\?.recordingSummary/)
  assert.match(settingsJs, /FdcVehicle\.displayName\(session\?\.vehicleName/)
  assert.match(settingsJs, /formatPatternSummary.*session\.stats/)
  assert.match(settingsJs, /formatPatternHeadline/)
  assert.match(settingsJs, /patternSummary\.text/)
  assert.match(settingsJs, /formatSummaryMetrics\?\.\(session\.stats\)/)
  assert.match(settingsJs, /recording\.sessions\.length === 1\s*\n\s*\? globalScope\.DriverAnalysisHistory\?\.recordingSummary/)
  assert.match(settingsJs, /function driverAnalysisSummaryTiles/)
  assert.match(settingsJs, /className = 'driver-analysis-detail-view__summary'/)
  assert.match(settingsJs, /className = 'driver-analysis-detail-view__result'/)
  assert.match(settingsJs, /formatStatsRows.*session\.stats/)
  assert.match(settingsJs, /if \(statsRows\.length > 0\)/)
  assert.match(settingsJs, /detailsButton\.textContent = 'DETAILS'/)
  assert.match(settingsJs, /events-run-table__lap-row/)
  assert.match(settingsJs, /events-run-table-section/)
  assert.match(settingsJs, /section\.title = statsRow\.title/)
  assert.match(settingsJs, /isDriverAnalysisPanelVisible && driverAnalysisView\.level !== 'history'/)
  assert.match(settingsJs, /events-lap-detail/)
  assert.match(settingsJs, /textContent = 'CARS'/)
  assert.match(settingsJs, /textContent = 'DRIVES'/)
  assert.match(settingsJs, /sectionH3\.textContent = /)
  assert.match(settingsCss, /\.driver-analysis-history-row__details-toggle,\s*\.driver-analysis-history-row__export,\s*\.driver-analysis-history-row__delete\s*\{\s*min-width:\s*84px/)
  assert.match(settingsJs, /actions\.append\(detailsButton\)[\s\S]*actions\.append\(exportButton, remove\)/)
  assert.match(settingsHtml, /id="destructive-confirm-dialog" class="confirm-dialog" role="alertdialog"[^>]+hidden/)
  assert.match(settingsHtml, /<h3 id="destructive-confirm-title">ARE YOU SURE\?<\/h3>/)
  assert.match(settingsHtml, /id="destructive-confirm-yes"[^>]*>YES<\/button>\s*<button id="destructive-confirm-no"[^>]*>NO<\/button>/)
  assert.match(settingsCss, /\.driver-analysis-history-row__summary\s*\{[\s\S]*margin-top:\s*8px/)
  assert.match(settingsCss, /\.driver-analysis-detail-view__body[\s\S]*display:\s*grid/)
  assert.match(settingsCss, /\.driver-analysis-detail-view__summary\s*\{[\s\S]*grid-template-columns:\s*repeat\(4, minmax\(0, 1fr\)\)/)
})

test('Back buttons on drill-down views name their parent and use detail-back class', () => {
  assert.match(settingsHtml, /id="events-detail-back"[^>]*class="detail-back"/)
  assert.match(settingsHtml, /id="events-detail-back"[^>]*aria-label="Back to Events"/)
  assert.match(settingsHtml, /id="events-detail-back"[^>]*>← EVENTS</)
  assert.match(settingsHtml, /id="events-run-back"[^>]*class="detail-back"/)
  assert.match(settingsHtml, /id="events-run-back"[^>]*aria-label="Back to the event"/)
  assert.match(settingsHtml, /id="events-run-back"[^>]*>← EVENT</)
  assert.match(settingsHtml, /id="driver-analysis-detail-back"[^>]*class="detail-back"/)
  // One rule decides where BACK leads; the label and the navigation both use it.
  assert.match(settingsJs, /function driverAnalysisParentLevel\(view\)/)
  assert.match(settingsJs, /DRIVER_ANALYSIS_BACK_LABELS\[driverAnalysisParentLevel\(next\)\]/)
  const closeLevel = settingsJs.match(/function closeDriverAnalysisLevel\(\) \{[\s\S]*?\r?\n  \}\r?\n/)[0]
  assert.match(closeLevel, /const parentLevel = driverAnalysisParentLevel\(driverAnalysisView\)/)
  assert.doesNotMatch(closeLevel, /groupRecordings/)
  assert.match(settingsJs, /driverAnalysisDetailBack\.textContent = label\.text/)
  assert.match(settingsJs, /driverAnalysisDetailBack\.setAttribute\('aria-label', label\.ariaLabel\)/)
  assert.match(settingsJs, /← HISTORY/)
  assert.match(settingsJs, /← RECORDING/)
  assert.match(settingsJs, /← CAR/)
})

test('Garage does not create image placeholders for current car or saved cars', () => {
  assert.doesNotMatch(settingsJs, /garage-current-car__image/)
  assert.doesNotMatch(settingsJs, /garage-card__image/)
  assert.doesNotMatch(settingsJs, /image\.textContent = 'IMAGE'[\s\S]*garageDisplayName/)
})

test('Configuration only calls render functions it defines, with the run they need', () => {
  const called = new Set([...settingsJs.matchAll(/\b(render[A-Z]\w*)\(/g)].map(match => match[1]))
  const defined = new Set([...settingsJs.matchAll(/function (render[A-Z]\w*)\(/g)].map(match => match[1]))
  assert.deepEqual([...called].filter(name => !defined.has(name)), [])
  assert.doesNotMatch(settingsJs, /renderEventRunDetail\(\)/)
})

test('Configuration uses one shared empty-state style', () => {
  assert.match(settingsCss, /\.settings-empty\s*\{/)
  assert.match(settingsCss, /\.settings-empty--inline\s*\{/)
  assert.match(settingsCss, /\.settings-empty\[hidden\]/)
  for (const id of ['driver-analysis-history-empty', 'garage-grid-empty', 'events-grid-empty', 'event-runs-empty', 'events-run-empty', 'shift-light-empty']) {
    assert.match(settingsHtml, new RegExp(`id="${id}"[^>]*class="settings-empty"`), id)
  }
  assert.match(settingsHtml, /id="garage-current-empty"[^>]*class="settings-empty settings-empty--inline"/)
  assert.doesNotMatch(settingsHtml, /garage-empty/)
  assert.doesNotMatch(settingsHtml, /driver-analysis-history__empty/)
  assert.doesNotMatch(settingsHtml, /event-runs__empty/)
  assert.doesNotMatch(settingsHtml, /calibration-empty/)
  assert.doesNotMatch(settingsCss, /garage-empty/)
  assert.doesNotMatch(settingsCss, /driver-analysis-history__empty/)
  assert.doesNotMatch(settingsCss, /event-runs__empty/)
  assert.doesNotMatch(settingsCss, /calibration-empty/)
  assert.match(settingsJs, /className = 'settings-empty'/)
  assert.doesNotMatch(settingsJs, /className = 'events-run-empty'/)
  assert.match(settingsCss, /\.shift-light-brightness-card__heading\s*\{[^}]*align-items:\s*center/)
})

test('Units module is loaded after vehicle in both overlay and settings HTML', () => {
  const overlayVehicleIndex = overlayHtml.indexOf('src="vehicle.js"')
  const overlayUnitsIndex = overlayHtml.indexOf('src="units.js"')
  const settingsVehicleIndex = settingsHtml.indexOf('src="vehicle.js"')
  const settingsUnitsIndex = settingsHtml.indexOf('src="units.js"')

  assert.ok(overlayVehicleIndex >= 0)
  assert.ok(overlayUnitsIndex > overlayVehicleIndex)
  assert.ok(settingsVehicleIndex >= 0)
  assert.ok(settingsUnitsIndex > settingsVehicleIndex)
})

test('Settings has distance unit controls wired alongside speed unit controls', () => {
  assert.match(settingsJs, /const distanceUnitInputs = \[\.\.\.document\.querySelectorAll\('input\[name="distance-unit"\]'\)\]/)
  assert.match(settingsJs, /distanceUnit: 'km'/)
  assert.match(settingsJs, /for \(const input of distanceUnitInputs\)/)
  assert.match(settingsJs, /updateDisplayPreferences\(\s*\{ distanceUnit: input\.value \},/)
  assert.match(settingsJs, /DISTANCE UNIT SET TO/)
  assert.match(settingsJs, /distanceUnit === 'mi' \? 'MI' : 'KM'/)
})

test('Settings re-renders unit-dependent views when units change', () => {
  assert.match(settingsJs, /function renderUnitDependentViews\(\)/)
  assert.match(settingsJs, /renderDriverAnalysisHistory\(\)/)
  assert.match(settingsJs, /renderDriverAnalysisView\(\)/)
  assert.match(settingsJs, /function renderUnitDependentViews\(\) \{[\s\S]*?renderEventRunDetail\(currentEventRun\)/)
  assert.match(settingsJs, /unitsChanged = previous\.speedUnit !== next\.speedUnit \|\| previous\.distanceUnit !== next\.distanceUnit/)
  assert.match(settingsJs, /if \(unitsChanged\) \{\s*renderUnitDependentViews\(\)/)
})

test('HUD DISPLAY card allows selecting which monitor the HUD covers', () => {
  const hudPanel = settingsHtml.slice(settingsHtml.indexOf('id="hud-panel"'), settingsHtml.indexOf('id="hud-panel"') + 4000)
  assert.match(hudPanel, /id="hud-display-title">HUD DISPLAY/)
  assert.match(hudPanel, /Monitor the HUD is shown on/)
  assert.match(hudPanel, /id="hud-display"[^>]*><\/select>/)
  assert.match(hudPanel, /id="hud-display-missing"[^>]*hidden/)
  assert.ok(hudPanel.indexOf('HUD DISPLAY') < hudPanel.indexOf('HUD OPACITY'))
  assert.match(settingsJs, /async function refreshHudDisplay/)
  assert.match(settingsJs, /call\('list_hud_displays'\)/)
  assert.match(settingsJs, /call\('set_hud_display'/)
  assert.match(settingsJs, /hudDisplay\.disabled = hudDisplayCount <= 1 \|\| Boolean\(editingTarget\)/)
  assert.match(settingsJs, /globalScope\.SettingsController[\s\S]*refreshHudDisplay/)
})

test('HUD uses FdcUnits for speed formatting and reads fresh display preferences on update', () => {
  assert.match(overlayHtml, /src="units.js"/)
  assert.match(overlayHtml, /src="vehicle.js"/)
  assert.ok(overlayHtml.indexOf('vehicle.js') < overlayHtml.indexOf('units.js'))
  const overlaySource = fs.readFileSync(path.join(__dirname, 'overlay.js'), 'utf8')
  assert.match(overlaySource, /window\.FdcUnits\.formatSpeed\([\s\S]*?\{ unit: displayPreferences\.speedUnit \}/)
  assert.match(overlaySource, /window\.DisplayPreferences\.write\(\{\s*\.\.\.window\.DisplayPreferences\.read\(\),/)
})

test('Drill-down views show a back link and page name in the header path', () => {
  const header = settingsHtml.slice(settingsHtml.indexOf('<header class="settings-header">'), settingsHtml.indexOf('</header>'))
  const path = header.slice(header.indexOf('class="settings-header__path"'), header.indexOf('</nav>'))
  for (const id of ['events-detail-back', 'events-run-back', 'driver-analysis-detail-back']) {
    assert.match(path, new RegExp(`id="${id}" class="detail-back"`), id)
    assert.equal(settingsHtml.split(`id="${id}"`).length, 2, `${id} appears once`)
  }
  for (const page of ['event', 'run', 'recording', 'car', 'drive']) {
    assert.match(path, new RegExp(`data-detail-page="${page}"`), page)
  }
  assert.doesNotMatch(settingsHtml, /class="events-detail-view__header"/)
  assert.match(settingsHtml, /class="events-detail-view__heading">\s*<button id="events-detail-title"[\s\S]*?class="events-detail-view__actions">\s*<button id="events-detail-delete"/)
  assert.match(settingsJs, /driverAnalysisDetailView\.dataset\.level = next\.level/)
  assert.match(settingsCss, /#driver-analysis-detail-view:not\(\[hidden\]\)\[data-level='car'\]\)\s*\[data-detail-page='car'\]/)
})

test('The one next step of a screen uses the lime ready button', () => {
  assert.match(settingsHtml, /id="events-create-toggle" class="settings-button settings-button--ready"/)
  assert.match(settingsHtml, /id="events-create-submit" class="settings-button settings-button--ready"/)
  assert.match(settingsJs, /detailsButton\.className = 'settings-button settings-button--ready driver-analysis-history-row__details-toggle'/)
  assert.doesNotMatch(settingsHtml, /settings-button--primary/)
  assert.match(settingsStyles, /\.settings-button\.settings-button--ready\s*\{[^}]*background: var\(--accent\)/)
  assert.match(settingsStyles, /\.settings-button\.settings-button--ready:disabled\s*\{[^}]*background: var\(--surface-deep\)/)
})

test('the HUD tab offers an edit hotkey in the layout edit row that is registered at startup and never shared with Driver Analysis', () => {
  const start = settingsHtml.indexOf('data-settings-panel="hud"')
  const hudPanel = settingsHtml.slice(start, settingsHtml.indexOf('data-settings-panel="', start + 1))
  assert.match(hudPanel, /data-layout-edit-row[\s\S]*id="hud-edit-hotkey-value"[^>]*>Ctrl \+ Shift \+ F8<\/output>/)
  // The hotkey row matches GLOBAL RECORD HOTKEY: copy on the left, the combination and CHANGE on the right.
  assert.match(hudPanel, /<strong>IN-GAME EDIT HOTKEY<\/strong>\s*<small id="hud-edit-hotkey-help">[^<]+<\/small>\s*<\/div>\s*<div class="action-panel__actions">\s*<output id="hud-edit-hotkey-value"[^>]*>Ctrl \+ Shift \+ F8<\/output>\s*<button id="hud-edit-hotkey-change" class="settings-button"/)
  assert.match(settingsStyles, /\.driver-analysis-hotkey__control output,\s*\.action-panel__actions output \{/)
  assert.doesNotMatch(hudPanel, /id="hud-edit-hotkey-title">EDIT HOTKEY/)
  assert.match(settingsJs, /const DEFAULT_HUD_EDIT_HOTKEY = 'Ctrl\+Shift\+F8'/)
  assert.match(settingsJs, /const HUD_EDIT_HOTKEY_STORAGE_KEY = 'fdc\.hud-edit-hotkey\.v1'/)
  assert.match(settingsJs, /call\('set_hud_edit_hotkey', \{ hotkey: normalized \}\)/)
  assert.match(settingsJs, /void setHudEditHotkey\(hudEditHotkeySettings\.hotkey, false, hudEditHotkeySettings\.hotkeyLabel\)/)
  assert.match(settingsJs, /THAT HOTKEY IS ALREADY USED BY DRIVER ANALYSIS/)
  assert.match(settingsJs, /THAT HOTKEY IS ALREADY USED BY HUD EDIT/)
  // One capture at a time: starting either capture ends the other.
  assert.match(settingsJs, /if \(hudEditHotkeyCapture && driverAnalysisHotkeyCapture\) await setDriverAnalysisHotkeyCapture\(false\)/)
  assert.match(settingsJs, /if \(driverAnalysisHotkeyCapture && hudEditHotkeyCapture\) await setHudEditHotkeyCapture\(false\)/)
  assert.match(tauriMain, /fn set_hud_edit_hotkey\(/)
  assert.match(tauriMain, /window\.HudLayout\?\.toggleEditSession\?\.\(\)/)
})

test('every widget switch is the only element bound to its widget', () => {
  for (const name of ['tires', 'pedals', 'steering', 'gear', 'engine', 'history']) {
    assert.equal(settingsHtml.match(new RegExp(`data-hud-toggle="${name}"`, 'g'))?.length, 1, name)
  }
  assert.equal(settingsHtml.match(/data-overlay-toggle="delta"/g)?.length, 1)
})
