/* Static, local-only proposal screens for the FDC design book.
   Values are visual fixtures drawn from supplied screenshots and current UI contracts. */
(() => {
  const badge = (text, tone = '') => `<span class="badge ${tone}">${text}</span>`;
  const panel = (title, body, extra = '') => `<section class="panel ${extra}"><div class="panel-head"><h3>${title}</h3></div>${body}</section>`;
  const metric = (label, value, tone = '') => `<div class="metric"><span class="label">${label}</span><strong class="num ${tone}">${value}</strong></div>`;
  const toggle = (on = true, label = 'Enabled') => `<button class="toggle" type="button" role="switch" aria-checked="${on}" data-demo="toggle" aria-label="${label}"><i></i></button>`;
  const bar = (title, value, amount, tone = 'green') => `<div class="range-card"><div class="row"><div><span class="label">VISUAL OUTPUT</span><strong>${title}</strong></div><strong class="num ${tone}">${value}%</strong></div><input type="range" min="0" max="100" value="${amount}" aria-label="${title}" data-demo="range"><div class="row muted range-scale"><span>0 · DIM</span><span>80 · DEFAULT</span><span>100 · MAX</span></div></div>`;
  const table = (heads, rows, cls = '') => `<div class="table-wrap"><table class="table ${cls}"><thead><tr>${heads.map(x => `<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(row => `<tr>${row.map((x, i) => `${i ? '<td' : '<th scope="row"'}>${x}${i ? '</td>' : '</th>'}`).join('')}</tr>`).join('')}</tbody></table></div>`;
  const details = (summary, content, open = false) => `<details ${open ? 'open' : ''}><summary>${summary}</summary><div class="details-body">${content}</div></details>`;
  const carClass = (c, label) => `<span class="badge class-${c}">${label}</span>`;
  const trace = `<svg viewBox="0 0 720 380" role="img" aria-label="Example lap input trace with throttle, brake and coast"><rect width="720" height="380" fill="#0d1211"/><g fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="7"><path d="M150 330 C190 300 180 265 240 245 S310 210 290 178 S275 130 340 113 S420 103 425 68 S390 39 365 52 S375 91 420 95 S500 80 515 135 S500 210 535 241 S570 310 540 330 S480 320 455 290 S395 265 365 290 S290 345 260 315 S225 282 205 303" stroke="#c3ed83"/><path d="M242 245 l15 -16 M295 178 l12 -22 M369 53 l5 15 M522 137 l13 20 M545 244 l12 23 M266 317 l-14 9" stroke="#f05b52"/></g><g fill="#eef1e4" font-family="sans-serif" font-size="14" font-weight="700"><text x="264" y="228">S1</text><text x="410" y="104">S2</text><text x="541" y="228">S3</text></g><circle cx="150" cy="330" r="7" fill="#fff"/></svg>`;

  window.FDC_SCREENS = [
    {
      id: 'hud-config', title: 'HUD · Layout controls', section: 'HUD',
      description: 'Settings page proposal. Controls mirror current layout modes, opacity, and visibility preferences.',
      html: `${bar('HUD OPACITY', 80, 80)}
        ${panel('HUD LAYOUT', `<div class="row"><div><strong>TELEMETRY ARRANGEMENT</strong><p class="muted">Choose how the on-screen instruments are arranged.</p></div><div class="segmented" role="group" aria-label="HUD layout"><button class="selected" data-demo="select">GROUPED</button><button data-demo="select">FREEFORM</button></div></div><div class="row divider"><div><strong>TELEMETRY HUD</strong><p class="muted">Show the compact driving display over the game.</p></div>${toggle(true, 'Telemetry HUD')}</div>`, 'plate')}
        ${panel('VISIBLE COMPONENTS', `<div class="grid2">${['TIRES & TEMPERATURES','PEDALS','STEERING','GEAR · SPEED · RPM','ENGINE DATA','INPUT HISTORY','DELTA'].map((x,i)=>`<div class="row compact"><span>${x}</span>${toggle(i !== 6, x)}</div>`).join('')}</div>`)}`
    },
    {
      id: 'hud-live', title: 'HUD · On-track specimen', section: 'HUD',
      description: 'Static on-screen HUD specimen based on current overlay consumers. Telemetry values are illustrative fixtures.',
      html: `<div class="hud-preview plate"><div class="hud-topline"><span class="label">FH6 · TELEMETRY</span><span class="badge green">LIVE DATA EXAMPLE</span></div><div class="hud-main grid3"><div class="instrument"><span class="label">SPEED</span><strong class="num huge">184</strong><span class="muted">KM/H</span></div><div class="instrument gear"><span class="label">GEAR</span><strong class="num huge">4</strong><span class="muted">6,240 RPM</span></div><div class="instrument"><span class="label">DELTA</span><strong class="num large green">−0.214</strong><span class="muted">TO BEST LAP</span></div></div><div class="grid2 hud-lower"><div class="instrument"><span class="label">THROTTLE</span><div class="meter"><i style="width:85%"></i></div><b class="num green">85%</b><span class="label">BRAKE</span><div class="meter brake"><i style="width:13%"></i></div><b class="num red">13%</b></div><div class="instrument"><span class="label">TYRES · °C</span><div class="row">FL ${metric('FRONT LEFT','84°')} ${metric('FRONT RIGHT','82°')}</div><div class="row">RL ${metric('REAR LEFT','79°')} ${metric('REAR RIGHT','80°')}</div></div></div><div class="row input-history"><span class="label">INPUT HISTORY</span><div class="sparkline"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div></div></div>`
    },
    {
      id: 'driver-list', title: 'Driver · Session history', section: 'DRIVER',
      description: 'Driver Analysis is an asphalt-only experimental review. Entries and measurements shown are sample data from the supplied screenshots.',
      html: `${panel('DRIVER ANALYSIS', `<div class="row"><div><span class="label green">EXPERIMENTAL · LOCAL RECORDINGS</span><p class="muted">Review repeated driving patterns from an asphalt session.</p></div>${toggle(true, 'Driver Analysis')}</div><div class="callout amber"><strong>BETA / MVP</strong><p>Experimental feedback can be inaccurate. Record on asphalt only. Recordings stay on this device until deleted.</p></div><div class="row divider"><div><strong>RECORD A SESSION</strong><p class="muted">FDC saves one recurring problem from an asphalt session.</p></div><span class="green label">READY</span><button class="button primary" data-demo="button">RECORD</button></div><div class="row divider"><div><strong>GLOBAL RECORD HOTKEY</strong><p class="muted">Works while Forza is in focus. Windows-key combinations are not allowed.</p></div><kbd>Ctrl + Shift + F9</kbd><button class="button" data-demo="button">CHANGE</button></div>`, 'plate')}
        ${panel('HISTORY <span class="label muted">3 RECORDINGS</span>', `<article class="history-row"><div class="history-meta"><strong>09/18/2026 · 07:26 PM</strong><span>33m 20s</span><span>54 MB</span></div><div><strong class="green">NO RECURRING PROBLEM DETECTED</strong><p class="muted">No single technique problem repeated often enough in this recording.</p></div><button class="button danger" data-demo="button">DELETE</button></article><article class="history-row"><div class="history-meta"><strong>09/18/2026 · 06:37 PM</strong><span>11m 37s</span><span>20 MB</span></div><div><strong class="green">NO RECURRING PROBLEM DETECTED</strong><p class="muted">No single technique problem repeated often enough in this recording.</p></div><button class="button danger" data-demo="button">DELETE</button></article><article class="history-row"><div class="history-meta"><strong>09/18/2026 · 06:03 PM</strong><span>7m 31s</span><span>13 MB</span></div><div><strong class="green">NO RECURRING PROBLEM DETECTED</strong><p class="muted">No single technique problem repeated often enough in this recording.</p></div><button class="button danger" data-demo="button">DELETE</button></article>`)}`
    },
    {
      id: 'driver-detail', title: 'Driver · Recording review', section: 'DRIVER',
      description: 'Expanded review state based on the currently inspected release build. Recorded values are fixtures; no track identity or ideal-line analysis is implied.',
      html: `<div class="callout amber"><strong>EXPERIMENTAL REVIEW</strong><p>One repeated pattern is summarized from this local asphalt recording. This is not a driving score.</p></div><div class="grid3">${metric('DISTANCE','5.9 km')}${metric('AVERAGE SPEED','150 km/h')}${metric('TOP SPEED','256 km/h')}</div>${panel('MOST FREQUENT · BRAKE + STEERING', `<p>Braking while steering was detected in <strong class="num">4 of 22 checks · 18%</strong>.</p><p class="muted">This pattern is reported as a problem only when it exceeds the current threshold.</p>`, 'plate')}${details('DETAILS · 6 CHECKS', table(['CHECKED MEASURE','OBSERVED'],[['PEDALS','6 full · 8 partial · 4 coast · 4 brake'],['STEERING','Median entry 31% · full lock 0%'],['BRAKING','Median decel 0.8 g · trail overlap 18%'],['CORNERS','Median lateral 0.7 g · 31 corners'],['ON POWER','Return after minimum speed 0.42 s']]), true)}`
    },
    {
      id: 'shift-light', title: 'Shift Light · Calibration', section: 'SHIFT LIGHT',
      description: 'Current calibration state and user controls. The example profile is illustrative and does not represent a live connection.',
      html: `${bar('REDLINE BRIGHTNESS', 85, 85, 'red')}<div class="row"><div><strong>FDC SHIFT LIGHT</strong><p class="muted">FDC shows the optimal shift cue in purple when available.</p></div>${toggle(true, 'FDC Shift Light')}</div>${bar('FDC SHIFT LIGHT BRIGHTNESS', 95, 95)}${panel('CURRENT CAR PROFILE', `<div class="grid3">${metric('CAR','FH6 CAR #1429')}${metric('PERFORMANCE INDEX','PI 800')}${metric('ENGINE LIMIT','8,200 RPM')}</div><div class="grid3">${metric('USABLE CEILING','7,940 RPM · 3/3')}${metric('CURRENT TARGET','OPTIMAL · 7,620 RPM')}${metric('STATE','OPTIMAL · GEAR 4','purple')}</div>${table(['GEAR','SHIFT POINT','ACCEPTED SHIFTS','STATE'],[['G2','6,940 RPM','12','OPTIMAL'],['G3','7,280 RPM','9','OPTIMAL'],['G4','7,620 RPM','6','OPTIMAL'],['G5','7,690 RPM','3','POTENTIAL']])}`, 'plate')}<button class="button danger" data-demo="button">RESET CURRENT CALIBRATION</button>`
    },
    {
      id: 'garage', title: 'Garage · Current car & variants', section: 'GARAGE',
      description: 'Garage uses telemetry-observed vehicle data. This proposal uses no vehicle image slots; IDs and labels below are examples.',
      html: `${panel('CURRENT CAR', `<div class="current-car"><div><span class="label">CAR ORDINAL</span><strong class="num large">1429</strong><p class="muted">GROUP 28</p><div class="row">${carClass('b','B')} ${badge('600')} ${badge('RWD')} ${badge('8 CYL')}</div></div><button class="button primary" data-demo="button">VIEW VARIANTS</button></div>`, 'plate')}${panel('OBSERVED VARIANTS <span class="label muted">VIEW · EXPANDED</span>', `<div class="variant-list">${[['B','600','RWD','8 CYL'],['A','700','RWD','8 CYL'],['S1','800','AWD','8 CYL'],['X','999','AWD','12 CYL']].map(v=>`<div class="variant-row">${carClass(v[0].toLowerCase(),' '+v[0]+' ')}<strong class="num">${v[1]}</strong><span>${v[2]}</span><span>${v[3]}</span><span class="muted">OBSERVED</span></div>`).join('')}</div>`) }${panel('SAVED CARS <span class="label muted">37 CARS · MOST RECENT FIRST</span>', `<div class="grid3">${[['1429','B','600'],['289','B','600'],['302','B','600'],['316','A','700'],['368','B','600'],['458','B','600']].map((v,i)=>`<article class="car-card"><div><strong class="num">${v[0]}</strong><div class="row">${carClass(v[1].toLowerCase(),v[1])}<span>${v[2]}</span></div></div>${i===0?'<span class="label amber">LAST USED</span>':''}</article>`).join('')}</div>`)}`
    },
    {
      id: 'events-library', title: 'Events · Library', section: 'EVENTS',
      description: 'The list and sorting controls follow the current event library. The event is from the user-supplied screenshots.',
      html: `<div class="row"><span class="label muted">SORT</span><select aria-label="Sort events" data-demo="select"><option>ID ↓</option><option>ID ↑</option><option>LAST RECORDED ↓</option><option>LAST RECORDED ↑</option></select><button class="button primary" data-demo="button">CREATE</button></div><article class="event-card plate"><div class="event-id num">#2</div><div><strong>Luta do Estadio</strong><div class="row">${badge('RIVALS','blue')}${badge('RALLY')}${carClass('s1','S1')}</div></div><span class="event-corner">OPEN →</span></article>`
    },
    {
      id: 'events-create', title: 'Events · Create', section: 'EVENTS',
      description: 'Creation form fields mirror current supported event metadata. This canvas form does not save an event.',
      html: `${panel('NEW EVENT', `<label class="field"><span>EVENT NAME</span><input placeholder="e.g. Luta do Estadio" value="Friday Rivals · Test Route" data-demo="input"></label><div class="grid2"><label class="field"><span>MODE</span><select data-demo="select"><option>Rivals</option><option>Any</option><option>Online</option><option>EventLab</option><option>Official</option><option>Blueprint</option></select></label><label class="field"><span>ROUTE TYPE</span><select data-demo="select"><option>Rally</option><option>Asphalt</option><option>Offroad</option></select></label><label class="field"><span>CAR CLASS</span><select data-demo="select"><option>S1</option>${['Any','D','C','B','A','S2','R','X'].map(x=>`<option>${x}</option>`).join('')}</select></label><label class="field"><span>NOTES · OPTIONAL</span><input placeholder="Add a note" data-demo="input"></label></div><div class="row actions"><button class="button" data-demo="button">CANCEL</button><button class="button primary" data-demo="button">CREATE EVENT</button></div>`, 'plate')}<div class="callout muted-box"><strong>SUPPORTED DETAILS</strong><p>Mode, route surface, class, and optional notes. Event identity comes from the user.</p></div>`
    },
    {
      id: 'events-detail', title: 'Events · Event details', section: 'EVENTS',
      description: 'Event detail view follows supplied Luta do Estadio screenshots and the current event/run structure.',
      html: `<div class="row divider" style="justify-content:flex-end"><button class="button danger" data-demo="button">DELETE</button></div><div class="row event-identity"><h2>Luta do Estadio</h2>${badge('#2')}${badge('RIVALS','blue')}${badge('RALLY')}${carClass('s1','S1')}</div><div class="best-time purple"><span class="label">ABSOLUTE BEST</span><strong class="num large">01:08.953</strong></div>${panel('RECORD RUNS <span class="label muted">6 RUNS</span>', `<div class="row"><span class="muted">For Sprint Racing, leave recording armed between attempts. Press STOP when you are done; if Forza omits the exact result, FDC uses the last live time.</span><button class="button primary" data-demo="button">RECORD RUN</button></div>${table(['ID','CAR','CLASS / PI / DRIVE','BEST','LAPS','DATE ↓'],[['8','1968 Tipo 33/2 Daytona','S1 · PI 800 · AWD','01:08.953','7','2026.09.16 18:47:09'],['7','1968 Tipo 33/2 Daytona','S1 · PI 800 · AWD','01:09.512','3','2026.09.16 18:42:59'],['6','1968 Tipo 33/2 Daytona','S1 · PI 800 · AWD','01:09.360','7','2026.09.16 18:34:04'],['5','1968 Tipo 33/2 Daytona','S1 · PI 800 · AWD','01:10.410','3','2026.09.16 18:29:30'],['4','1968 Tipo 33/2 Daytona','S1 · PI 800 · AWD','01:09.587','2','2026.09.16 18:25:34'],['3','1968 Tipo 33/2 Daytona','S1 · PI 800 · AWD','01:11.421','2','2026.09.16 18:22:29']])}`)}`
    },
    {
      id: 'events-run', title: 'Events · Run & lap detail', section: 'EVENTS',
      description: 'Lap rows, best-sector highlighting, trace, and pedal summary follow the user-supplied run screenshots. Times are fixtures.',
      html: `<div class="row event-identity"><h2>Luta do Estadio</h2>${badge('#2')}${badge('RIVALS','blue')}${badge('RALLY')}${carClass('s1','S1')}</div><div class="grid2"><div class="best-time purple"><span class="label">BEST HYPOTHETICAL TIME</span><strong class="num large">01:08.316</strong></div>${metric('RUN','#8')}</div>${panel('LAP BREAKDOWN <span class="label muted">SECTOR TIMES</span>', table(['LAP ↓','LAP TIME','SECTOR 1','SECTOR 2','SECTOR 3'],[['7','<span class="green">01:09.436</span>','<span class="green">00:27.289</span>','00:22.064','00:20.083'],['6','01:09.854','00:27.463','00:21.983','00:20.408'],['5','01:10.679','00:29.330','<span class="purple">00:21.341</span>','<span class="green">00:20.009</span>'],['4','<span class="purple">01:08.953</span>','<span class="purple">00:26.989</span>','<span class="green">00:21.978</span>','<span class="purple">00:19.986</span>'],['3','01:10.596','00:28.344','00:22.096','00:20.156'],['2','01:10.113','00:27.725','00:22.061','00:20.328'],['1','01:10.489','00:28.340','00:22.086','00:20.063']]), 'plate')}${details('LAP 7 · INPUT TRACE', `<div class="trace-layout"><div class="trace-map">${trace}</div><aside>${metric('THROTTLE','85%','green')}${metric('BRAKE','13%','red')}${metric('COAST','2%','amber')}<p class="muted">Input share across the saved lap.</p></aside></div>`, true)}`
    },
    {
      id: 'settings', title: 'Settings · App behavior', section: 'SETTINGS',
      description: 'Current app settings presented with proposed surface styling. Toggle and unit choices are demonstration controls.',
      html: `${panel('APP BEHAVIOR', `<div class="setting-row"><div><strong>CONFIGURATION ALWAYS ON TOP</strong><p class="muted">Keep Configuration above other apps and the game.</p></div>${toggle(false, 'Configuration always on top')}</div><div class="setting-row"><div><strong>SHOW HUD WITH TELEMETRY</strong><p class="muted">Show the HUD and Delta only while live telemetry is received.</p></div>${toggle(true, 'Show HUD with telemetry')}</div><div class="setting-row"><div><strong>SPEED UNIT</strong><p class="muted">Choose how speed is shown in the HUD, Events, and Driver Analysis.</p></div><div class="segmented" role="group" aria-label="Speed unit"><button class="selected" data-demo="select" aria-pressed="true">KM/H</button><button data-demo="select" aria-pressed="false">MPH</button></div></div><div class="setting-row"><div><strong>DISTANCE UNIT</strong><p class="muted">Choose how distances are shown in Events and Driver Analysis.</p></div><div class="segmented" role="group" aria-label="Distance unit"><button class="selected" data-demo="select" aria-pressed="true">KM</button><button data-demo="select" aria-pressed="false">MI</button></div></div>`, 'plate')}<div class="callout muted-box"><span class="label">DIRECT DATA OUT</span><p>Waiting for data · 127.0.0.1 : 5301</p></div>`
    }
  ];
})();

// Offline state is visible without implying a live vehicle profile.
window.FDC_SCREENS.find(b=>b.id==='shift-light').html += '<details><summary>Disconnected state · no live car profile</summary><div class="panel"><span class="label">WAITING FOR A LIVE CAR PROFILE</span><p class="muted">A profile appears when FDC receives telemetry for the current car.</p></div></details>';
