/* Human-readable companion to design-system.css. Values on this board are
   explicit so the next implementation phase has no color or type guesswork. */
(() => {
  const swatches = entries => `<div class="spec-grid">${entries.map(([name, variable, value]) => `<div class="spec-swatch" style="--sample:var(${variable})"><div class="spec-swatch__color"></div><strong>${name}</strong><code>${variable} · ${value}</code></div>`).join('')}</div>`;
  const rule = (name, text) => `<div class="spec-rule"><strong>${name}</strong><p>${text}</p></div>`;
  window.FDC_FOUNDATIONS.unshift({
    id: 'foundation-spec',
    title: 'Exact style specification',
    section: 'FOUNDATIONS',
    description: 'FDC Dark values for surface hierarchy, the two selected font families, compact detail headers and the unchanged in-game HUD. The source is design-system.css.',
    html: `<div class="row"><div><h2>FDC Dark specification</h2><p class="muted">Proposal 04 · painted app header, calm data surfaces, unchanged dark in-game HUD. <a href="design-system.css">Open the canonical CSS ↗</a></p></div><span class="badge green">DESIGN SOURCE / NOT RUNTIME</span></div>
      <section class="panel"><h3>BASE SURFACES AND TYPE</h3>${swatches([
        ['Background','--bg','#101715'],['UI surface','--surface','#1e2a22'],['Raised panel','--panel','#2c3b2f'],['Deep inset','--surface-deep','#152019'],['Hover surface','--surface-hover','#354b38'],['Subtle rule','--line-subtle','#405346'],['Painted header','--paint','#576a5b'],
        ['Instrument inset','--instrument','#101b15'],['In-game HUD','--hud-surface','#101b15'],['Widget edge','--hud-casing','#19241d'],['Grouped divider','--hud-divider','#344238'],['Primary text','--text','#edf0df'],['Text on lime','--text-on-accent','#162314'],['Text on red','--text-on-danger','#271615'],['Secondary text','--muted','#b0bcae'],['Rule / border','--line','#58695c'],['Casing edge','--line-strong','#8c9b82']
      ])}<p class="muted">Background, ordinary surface and raised panel now form visible levels. Data tables and navigation can use the deep inset without paint texture.</p></section>
      <section class="panel"><h3>ACTIONS AND MEANINGS</h3>${swatches([
        ['Action hover / selected','--lime','#c3ed83'],['Best / learned cue','--purple','#c39be7'],['Danger UI','--red','#f2877f'],['Attention UI','--amber','#e2c876'],
        ['Slip overlay','--cyan','#7dd3fc'],['Coast layer','--coast','#facc15']
      ])}<p class="muted">Color supplements a written label. Purple identifies the learned Shift Light cue and best time; the separate HUD colors below preserve telemetry meanings.</p></section>
      <section class="panel"><h3>IN-GAME HUD COLORS · EXISTING CONTRACT</h3>${swatches([
        ['Throttle / ahead','--telemetry-throttle','#69e83f'],['Brake / behind','--telemetry-brake','#ff312b'],['Cold tire','--tire-cold','#38bdf8'],
        ['Normal tire','--tire-normal','#69e83f'],['Warm tire','--tire-warm','#ffd400'],['Hot tire','--tire-hot','#ff312b']
      ])}<p class="muted">Tire ranges remain below 70°C, 70–&lt;82°C, 82–&lt;92°C and 92°C or above. These in-game meanings are distinct from the proposed Configuration accent palette.</p></section>
      <section class="panel"><h3>TYPOGRAPHY</h3><div class="spec-type-row"><b style="font-family:var(--font-ui);font-size:20px">Barlow · Navigation and body</b><span>Regular 400 / Semibold 600</span></div><div class="spec-type-row"><b style="font-family:var(--font-readout);font-size:35px">184 km/h · 8,796 RPM</b><span>Barlow Condensed · Medium 500 / Semibold 600</span></div>${rule('Scale','Top-level title 44 px · compact detail title 27 px · section 28 px · body 14 px · labels 11 px. Changing telemetry values and table columns use tabular numerals.')}${rule('Language','Application examples are English/Latin. Cyrillic glyph coverage has not been selected for the shipped UI.')}</section>
      <section class="panel"><h3>APP HIERARCHY</h3>${rule('Top-level header','Painted, textured app header with a 44 px title. Navigation remains visible below it.')}${rule('Detail header','Driver and Events drill-down pages use a compact single-row header with an immediate parent link and a 27 px title.')}${rule('Texture','The supplied paint.png appears on app headers at 90% texture opacity. Ordinary cards, forms, tables and in-game HUD surfaces have even fills.')}</section>
      <section class="panel"><h3>ACCENT AND SURFACE USE</h3>${rule('Raised panel','Use one raised olive plate for the main working area or principal result of a page. Supporting data stays on ordinary panels; do not raise every metric.')}${rule('Lime','Ordinary action buttons use lime fill on hover; selected navigation and choices keep a persistent lime fill. Lime text is reserved for compact ready or positive states and meaningful timing values, not decoration.')}${rule('Semantic results','Purple marks best or learned shift cues. Event modes, vehicle classes and map markers keep their established color maps. Within a comparison, keep each color tied to one meaning; use signs, labels and neutral text before adding another accent.')}${rule('Information hierarchy','Painted masthead = identity; raised plate = main object; warm white = normal information; muted green-grey = supporting information. Keep bright accents sparse so the next action and key result remain easy to find.')}</section>
      <section class="panel"><h3>HUD GEOMETRY AND RHYTHM</h3><div class="spec-cut"><strong>One dark strip / two outside cuts</strong><p>Flat in-game surface · no paint texture · opacity includes background and readings</p></div>${rule('Grouped HUD','One 736 × 69 px surface with six joined data areas and 0 px gutter. Only the outside top-left and bottom-right corners use a 14 px cut; subtle straight dividers separate readings.')}${rule('Freeform + Delta','Each independent widget and Delta uses a 7 px top-left and bottom-right cut at base scale. The gear stays one Speed / Gear / RPM block.')}${rule('Spacing','4 / 8 / 12 / 18 / 24 / 36 px rhythm. Borders are 1 px; controls remain square.')}</section>
      <section class="panel"><h3>HUD BEHAVIOR TO PRESERVE</h3>${rule('Overlay opacity','Whole HUD and Delta, including their dark backgrounds and readings: 1–100%, default 80%. The HUD specimen has a local slider to preview this.')}${rule('Scale and placement','Grouped moves and resizes as one target; Freeform moves and resizes six widgets separately. Each target retains the current 0.5×–2× edit range.')}${rule('Visibility','Selected edit target remains visible even when telemetry or a visibility switch would hide it. Save, Cancel, Escape and Reset retain their current meanings.')}</section>
      <section class="panel"><h3>EVENT MODES · PRESERVED COLORS</h3>${swatches([
        ['Any','--mode-any','#f97316'],['Rivals','--mode-rivals','#7dd3fc'],['Online','--mode-online','#facc15'],['EventLab','--mode-eventlab','#ffffff'],
        ['Official','--mode-official','#ef4444'],['Blueprint','--mode-blueprint','#c084fc']
      ])}<p class="muted">Any and EventLab badges use dark text for contrast.</p></section>
      <section class="panel"><h3>VEHICLE CLASSES · PRESERVED COLORS</h3>${swatches([
        ['D','--class-d','#7dd3fc'],['C','--class-c','#facc15'],['B','--class-b','#f97316'],['A','--class-a','#ef4444'],
        ['S1','--class-s1','#c084fc'],['S2','--class-s2','#2563eb'],['R','--class-r','#ec4899'],['X','--class-x','#22c55e']
      ])}</section>
      <section class="panel"><h3>DRIVER MAP · PRESERVED MARKERS</h3>${swatches([
        ['Front scrub','--problem-scrub','#fb923c'],['Exit wheelspin','--problem-wheelspin','#f472b6'],['Brake + steering','--problem-brake-steering','#818cf8'],['Abrupt release','--problem-release','#d8b4fe'],['Clean check','--problem-clean','#a1a1aa']
      ])}</section>
      <section class="panel"><h3>INTERACTION STATES</h3>${rule('Action buttons · trial','Primary and secondary actions use lime fill with dark text on hover. Destructive actions keep red text at rest and use red fill with dark text on hover. Primary actions keep a stronger border at rest.')}${rule('Focus','2 px lime outline with 4 px offset; a visible keyboard path for buttons, links and form controls.')}${rule('Selected','Lime fill on selected navigation and segmented choices remains visible without hover; pressed state is exposed through ARIA.')}${rule('Disabled','Reduced contrast and no hover action. Destructive buttons retain red text plus the DELETE label at rest.')}${rule('Loading / offline','Show WAITING or a named unavailable state; never present illustrative fixtures as live telemetry.')}</section>`
  });
})();
