use serde::Deserialize;
use std::collections::HashMap;
use std::sync::OnceLock;

// Generated by tools/update-vehicle-catalog.mjs; see docs/vehicle-catalog.md.
const CATALOG_JSON: &str = include_str!("../data/vehicle-catalog.json");

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct CatalogVehicle {
    ordinal: i32,
    name: String,
    car_type: Option<String>,
}

#[derive(Deserialize)]
struct CatalogFile {
    schema: i32,
    game: String,
    vehicles: Vec<CatalogVehicle>,
}

struct Entry {
    name: String,
    car_type: Option<String>,
}

static CATALOG: OnceLock<HashMap<i32, Entry>> = OnceLock::new();

fn load_catalog() -> HashMap<i32, Entry> {
    match serde_json::from_str::<CatalogFile>(CATALOG_JSON) {
        Ok(file) => file
            .vehicles
            .into_iter()
            .filter(|vehicle| vehicle.ordinal > 0 && !vehicle.name.is_empty())
            .map(|vehicle| {
                (
                    vehicle.ordinal,
                    Entry {
                        name: vehicle.name,
                        car_type: vehicle.car_type,
                    },
                )
            })
            .collect(),
        Err(error) => {
            // The catalog is embedded and tested at build time; an unreadable one
            // must not stop FDC, so every car falls back to its ordinal.
            eprintln!("unable to parse vehicle catalog: {error}");
            HashMap::new()
        }
    }
}

fn catalog() -> &'static HashMap<i32, Entry> {
    CATALOG.get_or_init(load_catalog)
}

/// The catalog name for a car ordinal, or `#<ordinal>` for a car the catalog does not know.
pub fn vehicle_name(ordinal: i32) -> String {
    catalog()
        .get(&ordinal)
        .map(|entry| entry.name.clone())
        .unwrap_or_else(|| format!("#{ordinal}"))
}

/// The catalog car type for a car ordinal, when the catalog has one.
pub fn vehicle_car_type(ordinal: i32) -> Option<String> {
    catalog()
        .get(&ordinal)
        .and_then(|entry| entry.car_type.clone())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    fn catalog_file() -> CatalogFile {
        serde_json::from_str(CATALOG_JSON).expect("the embedded vehicle catalog must parse")
    }

    #[test]
    fn embedded_catalog_is_valid() {
        let file = catalog_file();
        assert_eq!(file.schema, 1);
        assert_eq!(file.game, "fh6");
        assert!(!file.vehicles.is_empty());
        let mut ordinals = HashSet::new();
        for vehicle in &file.vehicles {
            assert!(
                vehicle.ordinal > 0,
                "ordinal {} must be positive",
                vehicle.ordinal
            );
            assert!(
                ordinals.insert(vehicle.ordinal),
                "ordinal {} is repeated",
                vehicle.ordinal
            );
            assert!(
                !vehicle.name.is_empty(),
                "ordinal {} has no name",
                vehicle.ordinal
            );
            assert!(
                vehicle.car_type.as_deref() != Some(""),
                "ordinal {} has an empty car type",
                vehicle.ordinal
            );
        }
        assert_eq!(catalog().len(), file.vehicles.len());
    }

    #[test]
    fn known_ordinals_resolve_name_and_car_type() {
        assert_eq!(vehicle_name(247), "1969 Toyota 2000GT");
        assert_eq!(vehicle_car_type(247).as_deref(), Some("Rare Classics"));
        assert_eq!(vehicle_name(2363), "2016 Ford Phoenix");
        assert_eq!(vehicle_car_type(2363), None);
    }

    #[test]
    fn unknown_ordinals_fall_back_to_the_ordinal() {
        // 2714 is an AI traffic bus, which the catalog leaves out.
        assert_eq!(vehicle_name(2714), "#2714");
        assert_eq!(vehicle_car_type(2714), None);
    }
}
